export type PathVideo = {
  id: string
  title: string
  channel: string
  duration: string
  why: string
  youtubeId?: string
  playlistId?: string
  url: string
}

export type PathPhase = {
  id: string
  step: number
  title: string
  blurb: string
  /** Optional habit bridge from Java / Spring / Node / .NET backends. */
  backendBridge: string
  videos: PathVideo[]
}

/** Validated YouTube library: backend engineer → production / agentic AI (oEmbed-checked). */
export const AGENTIC_PATH: PathPhase[] = [
  {
    id: 'python-for-ai',
    step: 1,
    title: 'Python for AI development',
    blurb: 'Backend fluency in Python: typing, packaging instincts, asyncio, FastAPI — enough to ship AI services.',
    backendBridge: 'Java / Spring / Node / .NET habits map to modules + FastAPI + pytest; List/Map → list/dict; typed DTOs → Pydantic.',
    videos: [
      {
        id: 'python-for-ai-jH85McHenvw',
        title: 'Learn Python by Thinking in Types - Full Course',
        channel: 'freeCodeCamp.org',
        duration: 'Video',
        why: 'Think in types early — the bridge from statically typed backends.',
        youtubeId: 'jH85McHenvw',
        url: 'https://www.youtube.com/watch?v=jH85McHenvw',
      },
      {
        id: 'python-for-ai-HGOBQPFzWKo',
        title: 'Intermediate Python Programming Course',
        channel: 'freeCodeCamp.org',
        duration: 'Video',
        why: 'Intermediate Python for engineers who already know another language.',
        youtubeId: 'HGOBQPFzWKo',
        url: 'https://www.youtube.com/watch?v=HGOBQPFzWKo',
      },
      {
        id: 'python-for-ai-Ej_02ICOIgs',
        title: 'Object Oriented Programming with Python - Full Course for Beginners',
        channel: 'freeCodeCamp.org',
        duration: 'Video',
        why: 'Classes, inheritance, and OOP patterns you’ll see in AI libraries.',
        youtubeId: 'Ej_02ICOIgs',
        url: 'https://www.youtube.com/watch?v=Ej_02ICOIgs',
      },
      {
        id: 'python-for-ai-TjA2V_yv-ko',
        title: 'Python Type Hints Explained for FastAPI Developers',
        channel: 'Analytics Vidhya',
        duration: 'Video',
        why: 'Type hints as FastAPI contracts — validation + OpenAPI for free.',
        youtubeId: 'TjA2V_yv-ko',
        url: 'https://www.youtube.com/watch?v=TjA2V_yv-ko',
      },
      {
        id: 'python-for-ai-Qb9s3UiMSTA',
        title: 'Asyncio in Python - Full Tutorial',
        channel: 'Tech With Tim',
        duration: 'Video',
        why: 'Asyncio event loop, tasks, gather — critical for LLM I/O concurrency.',
        youtubeId: 'Qb9s3UiMSTA',
        url: 'https://www.youtube.com/watch?v=Qb9s3UiMSTA',
      },
      {
        id: 'python-for-ai-0GVLtTnebNA',
        title: 'Learn Python\'s AsyncIO in 15 minutes',
        channel: 'Indently',
        duration: 'Video',
        why: 'Short asyncio refresher before FastAPI async routes.',
        youtubeId: '0GVLtTnebNA',
        url: 'https://www.youtube.com/watch?v=0GVLtTnebNA',
      },
      {
        id: 'python-for-ai-tLKKmouUams',
        title: 'FastAPI Course for Beginners',
        channel: 'freeCodeCamp.org',
        duration: 'Video',
        why: 'FastAPI crash course — the default Python service layer for AI apps.',
        youtubeId: 'tLKKmouUams',
        url: 'https://www.youtube.com/watch?v=tLKKmouUams',
      },
      {
        id: 'python-for-ai-0sOvCWFmrtA',
        title: 'Python API Development - Comprehensive Course for Beginners',
        channel: 'freeCodeCamp.org',
        duration: 'Video',
        why: 'Full FastAPI service: routes, Pydantic, SQL, pytest, CI/CD.',
        youtubeId: '0sOvCWFmrtA',
        url: 'https://www.youtube.com/watch?v=0sOvCWFmrtA',
      },
      {
        id: 'python-for-ai-QUT1VHiLmmI',
        title: 'Python NumPy Tutorial for Beginners',
        channel: 'freeCodeCamp.org',
        duration: 'Video',
        why: 'NumPy arrays only — useful mental model for embeddings/tensors, not a DS bootcamp.',
        youtubeId: 'QUT1VHiLmmI',
        url: 'https://www.youtube.com/watch?v=QUT1VHiLmmI',
      },
      {
        id: 'python-for-ai-eWRfhZUzrAc',
        title: 'Python for Beginners – Full Course [Programming Tutorial]',
        channel: 'freeCodeCamp.org',
        duration: 'Video',
        why: 'Optional: full Python reset if you’re new to the language.',
        youtubeId: 'eWRfhZUzrAc',
        url: 'https://www.youtube.com/watch?v=eWRfhZUzrAc',
      },
    ],
  },
  {
    id: 'llm-foundations',
    step: 2,
    title: 'LLM foundations',
    blurb: 'Understand models, transformers, and embeddings before wiring frameworks.',
    backendBridge: 'Treat the model like an unreliable remote dependency with latency, cost, and failure modes.',
    videos: [
      {
        id: 'llm-foundations-zjkBMFhNj_g',
        title: '[1hr Talk] Intro to Large Language Models',
        channel: 'Andrej Karpathy',
        duration: 'Video',
        why: 'Best 1-hour mental model of what LLMs are and aren’t.',
        youtubeId: 'zjkBMFhNj_g',
        url: 'https://www.youtube.com/watch?v=zjkBMFhNj_g',
      },
      {
        id: 'llm-foundations-7xTGNNLPyMI',
        title: 'Deep Dive into LLMs like ChatGPT',
        channel: 'Andrej Karpathy',
        duration: 'Video',
        why: 'Deep, systems-oriented dive into modern LLM training & inference.',
        youtubeId: '7xTGNNLPyMI',
        url: 'https://www.youtube.com/watch?v=7xTGNNLPyMI',
      },
      {
        id: 'llm-foundations-5sLYAQS9sWQ',
        title: 'How Large Language Models Work',
        channel: 'IBM Technology',
        duration: 'Video',
        why: 'Clear IBM explainer of how LLMs work end-to-end.',
        youtubeId: '5sLYAQS9sWQ',
        url: 'https://www.youtube.com/watch?v=5sLYAQS9sWQ',
      },
      {
        id: 'llm-foundations-wjZofJX0v4M',
        title: 'Transformers, the tech behind LLMs | Deep Learning Chapter 5',
        channel: '3Blue1Brown',
        duration: 'Video',
        why: 'Transformers visually — the architecture behind ChatGPT-class models.',
        youtubeId: 'wjZofJX0v4M',
        url: 'https://www.youtube.com/watch?v=wjZofJX0v4M',
      },
      {
        id: 'llm-foundations-eMlx5fFNoYc',
        title: 'Attention in transformers, step-by-step | Deep Learning Chapter 6',
        channel: '3Blue1Brown',
        duration: 'Video',
        why: 'Attention step-by-step — why context windows and KV cache matter.',
        youtubeId: 'eMlx5fFNoYc',
        url: 'https://www.youtube.com/watch?v=eMlx5fFNoYc',
      },
      {
        id: 'llm-foundations-FJtFZwbvkI4',
        title: 'How word vectors encode meaning',
        channel: '3Blue1Brown',
        duration: 'Video',
        why: 'Word vectors → meaning geometry — foundation for embeddings.',
        youtubeId: 'FJtFZwbvkI4',
        url: 'https://www.youtube.com/watch?v=FJtFZwbvkI4',
      },
      {
        id: 'llm-foundations-wgfSDrqYMJ4',
        title: 'What are Word Embeddings?',
        channel: 'IBM Technology',
        duration: 'Video',
        why: 'What embeddings are in plain language.',
        youtubeId: 'wgfSDrqYMJ4',
        url: 'https://www.youtube.com/watch?v=wgfSDrqYMJ4',
      },
      {
        id: 'llm-foundations-aircAruvnKk',
        title: 'But what is a neural network? | Deep learning chapter 1',
        channel: '3Blue1Brown',
        duration: 'Video',
        why: 'Neural net intuition if you want the math picture.',
        youtubeId: 'aircAruvnKk',
        url: 'https://www.youtube.com/watch?v=aircAruvnKk',
      },
      {
        id: 'llm-foundations-zxQyTK8quyY',
        title: 'Transformer Neural Networks, ChatGPT\'s foundation, Clearly Explained!!!',
        channel: 'StatQuest with Josh Starmer',
        duration: 'Video',
        why: 'Transformer overview without drowning in papers.',
        youtubeId: 'zxQyTK8quyY',
        url: 'https://www.youtube.com/watch?v=zxQyTK8quyY',
      },
      {
        id: 'llm-foundations-kCc8FmEb1nY',
        title: 'Let\'s build GPT: from scratch, in code, spelled out.',
        channel: 'Andrej Karpathy',
        duration: 'Video',
        why: 'Optional deep dive: build a GPT from scratch in code.',
        youtubeId: 'kCc8FmEb1nY',
        url: 'https://www.youtube.com/watch?v=kCc8FmEb1nY',
      },
      {
        id: 'llm-foundations-plGvCAUhRvKZ',
        title: 'Neural Networks: Zero to Hero',
        channel: 'Andrej Karpathy',
        duration: 'Playlist',
        why: 'Optional playlist: Karpathy Zero to Hero series.',
        playlistId: 'PLAqhIrjkxbuWI23v9cThsA9GvCAUhRvKZ',
        url: 'https://www.youtube.com/playlist?list=PLAqhIrjkxbuWI23v9cThsA9GvCAUhRvKZ',
      },
      {
        id: 'llm-foundations-5E-RdE6elMo',
        title: 'Mixture of Experts (MoE) spelled out | Implement from scratch | Pytorch | Python',
        channel: 'Saurav Prateek',
        duration: 'Video',
        why: 'MoE spelled out — useful for reading modern model cards.',
        youtubeId: '5E-RdE6elMo',
        url: 'https://www.youtube.com/watch?v=5E-RdE6elMo',
      },
      {
        id: 'llm-foundations-0TiJ9c9rzZA',
        title: 'LLMs: Vectors & Embeddings Explained Simply!',
        channel: 'The Geek Narrator',
        duration: 'Video',
        why: 'Vectors & embeddings for LLM engineers, simply.',
        youtubeId: '0TiJ9c9rzZA',
        url: 'https://www.youtube.com/watch?v=0TiJ9c9rzZA',
      },
    ],
  },
  {
    id: 'llm-apis-vectors',
    step: 3,
    title: 'LLM APIs, embeddings & vector DBs',
    blurb: 'Call models from Python, create embeddings, and store vectors like a production search service.',
    backendBridge: 'Same as any external API: keys, retries, timeouts, rate limits, cost dashboards — plus vector indexes as a search tier.',
    videos: [
      {
        id: 'llm-apis-vectors-uRQH2CFvedY',
        title: 'ChatGPT Course – Use The OpenAI API to Code 5 Projects',
        channel: 'freeCodeCamp.org',
        duration: 'Video',
        why: 'Hands-on OpenAI API projects — auth, chat completions, prompts.',
        youtubeId: 'uRQH2CFvedY',
        url: 'https://www.youtube.com/watch?v=uRQH2CFvedY',
      },
      {
        id: 'llm-apis-vectors-xZDB1naRUlk',
        title: 'Development with Large Language Models Tutorial – OpenAI, Langchain, Agents, Chroma',
        channel: 'freeCodeCamp.org',
        duration: 'Video',
        why: 'LLM app stack: OpenAI + LangChain + agents + Chroma in one course.',
        youtubeId: 'xZDB1naRUlk',
        url: 'https://www.youtube.com/watch?v=xZDB1naRUlk',
      },
      {
        id: 'llm-apis-vectors-6wkFb2_cUik',
        title: 'Tool use with the Claude 3 model family',
        channel: 'Anthropic',
        duration: 'Video',
        why: 'Official Anthropic tool-use patterns with Claude.',
        youtubeId: '6wkFb2_cUik',
        url: 'https://www.youtube.com/watch?v=6wkFb2_cUik',
      },
      {
        id: 'llm-apis-vectors-gl1r1XV0SLw',
        title: 'What is a Vector Database? Powering Semantic Search & AI Applications',
        channel: 'IBM Technology',
        duration: 'Video',
        why: 'Vector databases for semantic search & AI apps.',
        youtubeId: 'gl1r1XV0SLw',
        url: 'https://www.youtube.com/watch?v=gl1r1XV0SLw',
      },
      {
        id: 'llm-apis-vectors-dN0lsF2cvm4',
        title: 'Vector Databases simply explained! (Embeddings & Indexes)',
        channel: 'AssemblyAI',
        duration: 'Video',
        why: 'Embeddings & indexes — how vector DBs actually retrieve.',
        youtubeId: 'dN0lsF2cvm4',
        url: 'https://www.youtube.com/watch?v=dN0lsF2cvm4',
      },
      {
        id: 'llm-apis-vectors-klTvEwg3oJ4',
        title: 'Vector databases are so hot right now. WTF are they?',
        channel: 'Fireship',
        duration: 'Video',
        why: 'Quick, practical intuition for why vector DBs exploded.',
        youtubeId: 'klTvEwg3oJ4',
        url: 'https://www.youtube.com/watch?v=klTvEwg3oJ4',
      },
      {
        id: 'llm-apis-vectors-7G9q_5q82hY',
        title: 'How to Benchmark Embedding Models On Your Own Data',
        channel: 'freeCodeCamp.org',
        duration: 'Video',
        why: 'Benchmark embedding models on your own data — evals mindset.',
        youtubeId: '7G9q_5q82hY',
        url: 'https://www.youtube.com/watch?v=7G9q_5q82hY',
      },
      {
        id: 'llm-apis-vectors-mEsleV16qdo',
        title: 'Generative AI Full Course – Gemini Pro, OpenAI, Llama, Langchain, Pinecone, Vector Databases & More',
        channel: 'freeCodeCamp.org',
        duration: 'Video',
        why: 'Broad GenAI course covering APIs, LangChain, Pinecone, vectors.',
        youtubeId: 'mEsleV16qdo',
        url: 'https://www.youtube.com/watch?v=mEsleV16qdo',
      },
    ],
  },
  {
    id: 'tools-agents-basics',
    step: 4,
    title: 'Tool calling & first agents',
    blurb: 'Agents = model + tools + loop. Start with function calling, MCP, and LangChain components.',
    backendBridge: 'Tool schemas are interface contracts; validate args server-side like any API; never trust model output.',
    videos: [
      {
        id: 'tools-agents-basics-F8NKVhkZZWI',
        title: 'What are AI Agents?',
        channel: 'IBM Technology',
        duration: 'Video',
        why: 'What AI agents are — crisp definition.',
        youtubeId: 'F8NKVhkZZWI',
        url: 'https://www.youtube.com/watch?v=F8NKVhkZZWI',
      },
      {
        id: 'tools-agents-basics-IivxYYkJ2DI',
        title: 'AI Agents and AI Assistants: A Contrast in Function',
        channel: 'IBM Technology',
        duration: 'Video',
        why: 'Agents vs assistants — when each pattern fits.',
        youtubeId: 'IivxYYkJ2DI',
        url: 'https://www.youtube.com/watch?v=IivxYYkJ2DI',
      },
      {
        id: 'tools-agents-basics-jOCbjabknGk',
        title: 'AI Agents and AI Workflows are not the same | Agents Vs Workflows | Code walkthrough | Python',
        channel: 'Saurav Prateek',
        duration: 'Video',
        why: 'Agents vs workflows with Python walkthrough.',
        youtubeId: 'jOCbjabknGk',
        url: 'https://www.youtube.com/watch?v=jOCbjabknGk',
      },
      {
        id: 'tools-agents-basics-aqdWSYWC_LI',
        title: 'OpenAI Function Calling - Full Beginner Tutorial',
        channel: 'Dave Ebbelaar',
        duration: 'Video',
        why: 'OpenAI function calling fundamentals.',
        youtubeId: 'aqdWSYWC_LI',
        url: 'https://www.youtube.com/watch?v=aqdWSYWC_LI',
      },
      {
        id: 'tools-agents-basics-p0I-hwZSWMs',
        title: 'Function Calling with OpenAI APIs | A Crash Course',
        channel: 'Elvis Saravia',
        duration: 'Video',
        why: 'Function calling crash course for API-minded engineers.',
        youtubeId: 'p0I-hwZSWMs',
        url: 'https://www.youtube.com/watch?v=p0I-hwZSWMs',
      },
      {
        id: 'tools-agents-basics-Occy4R56hig',
        title: 'Tool Calling - Make LLMs talk to Database, APIs and Web | Langchain | Python',
        channel: 'Saurav Prateek',
        duration: 'Video',
        why: 'LangChain tool calling to DBs, APIs, and the web.',
        youtubeId: 'Occy4R56hig',
        url: 'https://www.youtube.com/watch?v=Occy4R56hig',
      },
      {
        id: 'tools-agents-basics-lG7Uxts9SXs',
        title: 'LangChain Crash Course for Beginners',
        channel: 'freeCodeCamp.org',
        duration: 'Video',
        why: 'LangChain components crash course.',
        youtubeId: 'lG7Uxts9SXs',
        url: 'https://www.youtube.com/watch?v=lG7Uxts9SXs',
      },
      {
        id: 'tools-agents-basics-xTmU8ZImUO8',
        title: 'LangChain Explained in 10 Minutes (Components Breakdown + Build Your First AI Chatbot)',
        channel: 'KodeKloud',
        duration: 'Video',
        why: 'LangChain in 10 minutes + first chatbot.',
        youtubeId: 'xTmU8ZImUO8',
        url: 'https://www.youtube.com/watch?v=xTmU8ZImUO8',
      },
      {
        id: 'tools-agents-basics-eur8dUO9mvE',
        title: 'What is MCP? Integrate AI Agents with Databases & APIs',
        channel: 'IBM Technology',
        duration: 'Video',
        why: 'MCP: connect agents to databases & APIs.',
        youtubeId: 'eur8dUO9mvE',
        url: 'https://www.youtube.com/watch?v=eur8dUO9mvE',
      },
      {
        id: 'tools-agents-basics-7j1t3UZA1TY',
        title: 'MCP vs API: Simplifying AI Agent Integration with External Data',
        channel: 'IBM Technology',
        duration: 'Video',
        why: 'MCP vs API — integration mental models.',
        youtubeId: '7j1t3UZA1TY',
        url: 'https://www.youtube.com/watch?v=7j1t3UZA1TY',
      },
      {
        id: 'tools-agents-basics-goU9VIXA8II',
        title: 'MCP vs Skills: Which Is Right for Your AI Agent and LLMs?',
        channel: 'IBM Technology',
        duration: 'Video',
        why: 'MCP vs skills — choosing agent extension styles.',
        youtubeId: 'goU9VIXA8II',
        url: 'https://www.youtube.com/watch?v=goU9VIXA8II',
      },
      {
        id: 'tools-agents-basics-lWt55CYtZNo',
        title: 'Model Context Protocol (MCP) from scratch | Connecting your AI Agents with external server and tools',
        channel: 'Saurav Prateek',
        duration: 'Video',
        why: 'Build MCP from scratch in Python.',
        youtubeId: 'lWt55CYtZNo',
        url: 'https://www.youtube.com/watch?v=lWt55CYtZNo',
      },
      {
        id: 'tools-agents-basics-ZUjijNrg5sQ',
        title: 'The Agent Development Lifecycle 101 by Harrison Chase',
        channel: 'LangChain',
        duration: 'Video',
        why: 'Agent development lifecycle from LangChain’s Harrison Chase.',
        youtubeId: 'ZUjijNrg5sQ',
        url: 'https://www.youtube.com/watch?v=ZUjijNrg5sQ',
      },
      {
        id: 'tools-agents-basics-AZDSpS5v57w',
        title: 'AI Agents For Beginners – OpenClaw Case Study',
        channel: 'freeCodeCamp.org',
        duration: 'Video',
        why: 'Beginner agent case study to cement the loop.',
        youtubeId: 'AZDSpS5v57w',
        url: 'https://www.youtube.com/watch?v=AZDSpS5v57w',
      },
      {
        id: 'tools-agents-basics-VswwV9RJN7s',
        title: 'OpenAI Function Calling Tutorial for Beginners',
        channel: 'Brainqub3',
        duration: 'Video',
        why: 'OpenAI function calling tutorial for beginners.',
        youtubeId: 'VswwV9RJN7s',
        url: 'https://www.youtube.com/watch?v=VswwV9RJN7s',
      },
    ],
  },
  {
    id: 'rag',
    step: 5,
    title: 'RAG systems',
    blurb: 'Ground answers in your data — the default enterprise pattern.',
    backendBridge: 'Index = search service; retriever = query API; generator = orchestration layer with caching and authz.',
    videos: [
      {
        id: 'rag-T-D1OfcDW1M',
        title: 'What is Retrieval-Augmented Generation (RAG)?',
        channel: 'IBM Technology',
        duration: 'Video',
        why: 'What RAG is and why enterprises use it.',
        youtubeId: 'T-D1OfcDW1M',
        url: 'https://www.youtube.com/watch?v=T-D1OfcDW1M',
      },
      {
        id: 'rag-_HQ2H_0Ayy0',
        title: 'RAG Explained For Beginners',
        channel: 'KodeKloud',
        duration: 'Video',
        why: 'RAG for beginners — clean mental model.',
        youtubeId: '_HQ2H_0Ayy0',
        url: 'https://www.youtube.com/watch?v=_HQ2H_0Ayy0',
      },
      {
        id: 'rag-UabBYexBD4k',
        title: 'Is RAG Still Needed? Choosing the Best Approach for LLMs',
        channel: 'IBM Technology',
        duration: 'Video',
        why: 'When RAG still wins vs long context / fine-tuning.',
        youtubeId: 'UabBYexBD4k',
        url: 'https://www.youtube.com/watch?v=UabBYexBD4k',
      },
      {
        id: 'rag-sVcwVQRHIc8',
        title: 'Learn RAG From Scratch – Python AI Tutorial from a LangChain Engineer',
        channel: 'freeCodeCamp.org',
        duration: 'Video',
        why: 'Build RAG from scratch with a LangChain engineer.',
        youtubeId: 'sVcwVQRHIc8',
        url: 'https://www.youtube.com/watch?v=sVcwVQRHIc8',
      },
      {
        id: 'rag-ea2W8IogX80',
        title: 'RAG Fundamentals and Advanced Techniques – Full Course',
        channel: 'freeCodeCamp.org',
        duration: 'Video',
        why: 'RAG fundamentals through advanced techniques.',
        youtubeId: 'ea2W8IogX80',
        url: 'https://www.youtube.com/watch?v=ea2W8IogX80',
      },
      {
        id: 'rag-wd7TZ4w1mSw',
        title: 'RAG From Scratch: Part 1 (Overview)',
        channel: 'LangChain',
        duration: 'Video',
        why: 'LangChain RAG From Scratch Part 1 — overview.',
        youtubeId: 'wd7TZ4w1mSw',
        url: 'https://www.youtube.com/watch?v=wd7TZ4w1mSw',
      },
      {
        id: 'rag-bjb_EMsTDKI',
        title: 'RAG From Scratch: Part 2 (Indexing)',
        channel: 'LangChain',
        duration: 'Video',
        why: 'LangChain RAG From Scratch Part 2 — indexing.',
        youtubeId: 'bjb_EMsTDKI',
        url: 'https://www.youtube.com/watch?v=bjb_EMsTDKI',
      },
      {
        id: 'rag-pliQ23ZztA0x',
        title: 'RAG From Scratch',
        channel: 'LangChain',
        duration: 'Playlist',
        why: 'Full LangChain RAG From Scratch playlist.',
        playlistId: 'PLfaIDFEXuae2LXbO1_PKyVJiQ23ZztA0x',
        url: 'https://www.youtube.com/playlist?list=PLfaIDFEXuae2LXbO1_PKyVJiQ23ZztA0x',
      },
      {
        id: 'rag-cDn7bf84LsM',
        title: 'LangChain RAG: Optimizing AI Models for Accurate Responses',
        channel: 'IBM Technology',
        duration: 'Video',
        why: 'Optimizing LangChain RAG for accurate responses.',
        youtubeId: 'cDn7bf84LsM',
        url: 'https://www.youtube.com/watch?v=cDn7bf84LsM',
      },
      {
        id: 'rag-TRjq7t2Ms5I',
        title: 'Building Production-Ready RAG Applications: Jerry Liu',
        channel: 'AI Engineer',
        duration: 'Video',
        why: 'Production-ready RAG patterns (Jerry Liu).',
        youtubeId: 'TRjq7t2Ms5I',
        url: 'https://www.youtube.com/watch?v=TRjq7t2Ms5I',
      },
      {
        id: 'rag-IWyUUrvmb2A',
        title: 'LlamaIndex tutorial in less than 15 mins ',
        channel: 'AI Bites',
        duration: 'Video',
        why: 'LlamaIndex in ~15 minutes as an alternative stack.',
        youtubeId: 'IWyUUrvmb2A',
        url: 'https://www.youtube.com/watch?v=IWyUUrvmb2A',
      },
      {
        id: 'rag-plHKbFD_RJfX',
        title: 'RAG Playlist',
        channel: 'CampusX',
        duration: 'Playlist',
        why: 'CampusX RAG playlist for extra practice.',
        playlistId: 'PLKnIA16_Rmva0dRLWEHLznSHKbFD_RJfX',
        url: 'https://www.youtube.com/playlist?list=PLKnIA16_Rmva0dRLWEHLznSHKbFD_RJfX',
      },
      {
        id: 'rag-plyt5yOFlz_6',
        title: 'RAG with LangGraph',
        channel: 'vijai sundaram',
        duration: 'Playlist',
        why: 'RAG with LangGraph patterns.',
        playlistId: 'PLEHeb1HGikpRX0---E12X1hyt5yOFlz_6',
        url: 'https://www.youtube.com/playlist?list=PLEHeb1HGikpRX0---E12X1hyt5yOFlz_6',
      },
    ],
  },
  {
    id: 'langgraph-agentic',
    step: 6,
    title: 'LangGraph & agentic workflows',
    blurb: 'Stateful graphs, loops, multi-agent, CrewAI / AutoGen patterns.',
    backendBridge: 'Think state machines / saga orchestration — nodes, edges, checkpoints, retries.',
    videos: [
      {
        id: 'langgraph-agentic-EDb37y_MhRw',
        title: 'Generative vs Agentic AI: Shaping the Future of AI Collaboration',
        channel: 'IBM Technology',
        duration: 'Video',
        why: 'Generative vs agentic AI — collaboration framing.',
        youtubeId: 'EDb37y_MhRw',
        url: 'https://www.youtube.com/watch?v=EDb37y_MhRw',
      },
      {
        id: 'langgraph-agentic-qAF1NjEVHhY',
        title: 'LangChain vs LangGraph: A Tale of Two Frameworks',
        channel: 'IBM Technology',
        duration: 'Video',
        why: 'LangChain vs LangGraph — when graphs win.',
        youtubeId: 'qAF1NjEVHhY',
        url: 'https://www.youtube.com/watch?v=qAF1NjEVHhY',
      },
      {
        id: 'langgraph-agentic-5h-JBkySK34',
        title: 'LangGraph: Intro',
        channel: 'LangChain',
        duration: 'Video',
        why: 'Official LangGraph intro.',
        youtubeId: '5h-JBkySK34',
        url: 'https://www.youtube.com/watch?v=5h-JBkySK34',
      },
      {
        id: 'langgraph-agentic-cUfLrn3TM3M',
        title: 'LangGraph Explained for Beginners',
        channel: 'KodeKloud',
        duration: 'Video',
        why: 'LangGraph explained for beginners.',
        youtubeId: 'cUfLrn3TM3M',
        url: 'https://www.youtube.com/watch?v=cUfLrn3TM3M',
      },
      {
        id: 'langgraph-agentic-jGg_1h0qzaM',
        title: 'LangGraph Complete Course for Beginners – Complex AI Agents with Python',
        channel: 'freeCodeCamp.org',
        duration: 'Video',
        why: 'Complete LangGraph course with Python agents.',
        youtubeId: 'jGg_1h0qzaM',
        url: 'https://www.youtube.com/watch?v=jGg_1h0qzaM',
      },
      {
        id: 'langgraph-agentic-hvAPnpSfSGo',
        title: 'LangGraph: Multi-Agent Workflows',
        channel: 'LangChain',
        duration: 'Video',
        why: 'Multi-agent workflows in LangGraph.',
        youtubeId: 'hvAPnpSfSGo',
        url: 'https://www.youtube.com/watch?v=hvAPnpSfSGo',
      },
      {
        id: 'langgraph-agentic-uRya4zRrRx4',
        title: 'LangGraph: Planning Agents',
        channel: 'LangChain',
        duration: 'Video',
        why: 'Plan-and-execute agents with LangGraph.',
        youtubeId: 'uRya4zRrRx4',
        url: 'https://www.youtube.com/watch?v=uRya4zRrRx4',
      },
      {
        id: 'langgraph-agentic-plgJ0w6Pkwtg',
        title: 'LangGraph (Python)',
        channel: 'LangChain',
        duration: 'Playlist',
        why: 'Official LangGraph (Python) playlist.',
        playlistId: 'PLfaIDFEXuae16n2TWUkKq5PgJ0w6Pkwtg',
        url: 'https://www.youtube.com/playlist?list=PLfaIDFEXuae16n2TWUkKq5PgJ0w6Pkwtg',
      },
      {
        id: 'langgraph-agentic-Zy7EXDONlTY',
        title: 'Agentic AI – Complete Course for Beginners',
        channel: 'freeCodeCamp.org',
        duration: 'Video',
        why: 'Agentic AI complete beginner course.',
        youtubeId: 'Zy7EXDONlTY',
        url: 'https://www.youtube.com/watch?v=Zy7EXDONlTY',
      },
      {
        id: 'langgraph-agentic-MnG0ugK2JAI',
        title: 'Build Your Own AI Agent – Full Course with OpenAI, Langchain, Render Deployment',
        channel: 'freeCodeCamp.org',
        duration: 'Video',
        why: 'Build and deploy an AI agent end-to-end.',
        youtubeId: 'MnG0ugK2JAI',
        url: 'https://www.youtube.com/watch?v=MnG0ugK2JAI',
      },
      {
        id: 'langgraph-agentic-G42J2MSKyc8',
        title: 'CrewAI Tutorial | Agentic AI Tutorial',
        channel: 'codebasics',
        duration: 'Video',
        why: 'CrewAI multi-agent tutorial.',
        youtubeId: 'G42J2MSKyc8',
        url: 'https://www.youtube.com/watch?v=G42J2MSKyc8',
      },
      {
        id: 'langgraph-agentic-DL6cGf7ZTlE',
        title: 'Prompt Chaining | Agentic Workflow Design Pattern | LangChain, LangGraph | Python',
        channel: 'Saurav Prateek',
        duration: 'Video',
        why: 'Prompt chaining as an agentic design pattern.',
        youtubeId: 'DL6cGf7ZTlE',
        url: 'https://www.youtube.com/watch?v=DL6cGf7ZTlE',
      },
      {
        id: 'langgraph-agentic-DUqWKsbqfM4',
        title: 'Learn Agent2Agent (A2A) Protocol | Build Your First Multi-Agent Network | Python',
        channel: 'Saurav Prateek',
        duration: 'Video',
        why: 'A2A protocol — multi-agent networks in Python.',
        youtubeId: 'DUqWKsbqfM4',
        url: 'https://www.youtube.com/watch?v=DUqWKsbqfM4',
      },
      {
        id: 'langgraph-agentic-V3pYAAWKET0',
        title: 'Understand Microsoft AutoGen 0.4 with a Mini Project (Multi-Agent)',
        channel: 'MadeForCloud',
        duration: 'Video',
        why: 'Microsoft AutoGen multi-agent mini project.',
        youtubeId: 'V3pYAAWKET0',
        url: 'https://www.youtube.com/watch?v=V3pYAAWKET0',
      },
      {
        id: 'langgraph-agentic-lEqjWjHZT0E',
        title: 'AutoGen Tutorial 🤖 Multi Agent Systems | Built in Classes Explained',
        channel: 'Simplified AI Course',
        duration: 'Video',
        why: 'AutoGen multi-agent systems overview.',
        youtubeId: 'lEqjWjHZT0E',
        url: 'https://www.youtube.com/watch?v=lEqjWjHZT0E',
      },
      {
        id: 'langgraph-agentic-plRRXVlQM0gR',
        title: 'LangGraph Series',
        channel: 'Yash Jain',
        duration: 'Playlist',
        why: 'LangGraph series for more practice.',
        playlistId: 'PLjuA_yqsfemenaOq4hjs3zTRRXVlQM0gR',
        url: 'https://www.youtube.com/playlist?list=PLjuA_yqsfemenaOq4hjs3zTRRXVlQM0gR',
      },
    ],
  },
  {
    id: 'production',
    step: 7,
    title: 'Prompting, evals & production habits',
    blurb: 'Prompt patterns, evaluation harnesses, roadmaps, and systems thinking beyond demos.',
    backendBridge: 'Same as any backend prod bar: SLOs, authz, audit logs, circuit breakers, cost budgets, regression tests.',
    videos: [
      {
        id: 'production-_ZvnD73m40o',
        title: 'Prompt Engineering Tutorial – Master ChatGPT and LLM Responses',
        channel: 'freeCodeCamp.org',
        duration: 'Video',
        why: 'Prompt engineering tutorial for reliable LLM responses.',
        youtubeId: '_ZvnD73m40o',
        url: 'https://www.youtube.com/watch?v=_ZvnD73m40o',
      },
      {
        id: 'production-1c9iyoVIwDs',
        title: '4 Methods of Prompt Engineering',
        channel: 'IBM Technology',
        duration: 'Video',
        why: 'IBM: RAG, CoT, ReAct, DSP — core prompt methods.',
        youtubeId: '1c9iyoVIwDs',
        url: 'https://www.youtube.com/watch?v=1c9iyoVIwDs',
      },
      {
        id: 'production-dOxUroR57xs',
        title: 'Prompt Engineering Overview',
        channel: 'Elvis Saravia',
        duration: 'Video',
        why: 'Prompt engineering overview for builders.',
        youtubeId: 'dOxUroR57xs',
        url: 'https://www.youtube.com/watch?v=dOxUroR57xs',
      },
      {
        id: 'production-pl-wElOmsxQT',
        title: 'AI Engineering 101',
        channel: 'Saurav Prateek',
        duration: 'Playlist',
        why: 'AI Engineering 101 playlist — practical systems habits.',
        playlistId: 'PL3tZ_eA1QJswSQrpDveVkIH-wElOmsxQT',
        url: 'https://www.youtube.com/playlist?list=PL3tZ_eA1QJswSQrpDveVkIH-wElOmsxQT',
      },
      {
        id: 'production-rSKh6bVuVZI',
        title: 'Everything Gets Rebuilt: The New AI Agent Stack | Harrison Chase, LangChain',
        channel: 'The MAD Podcast with Matt Turck',
        duration: 'Video',
        why: 'Harrison Chase on the new AI agent stack.',
        youtubeId: 'rSKh6bVuVZI',
        url: 'https://www.youtube.com/watch?v=rSKh6bVuVZI',
      },
      {
        id: 'production-39zbC_PrNQs',
        title: 'Roadmap to Become a Generative AI Expert for Beginners in 2025',
        channel: 'Analytics Vidhya',
        duration: 'Video',
        why: 'Generative AI learning roadmap for orientation.',
        youtubeId: '39zbC_PrNQs',
        url: 'https://www.youtube.com/watch?v=39zbC_PrNQs',
      },
    ],
  },
]

export function allPathVideos(): PathVideo[] {
  return AGENTIC_PATH.flatMap((p) => p.videos)
}

export function embedUrl(video: PathVideo): string {
  if (video.playlistId) {
    return `https://www.youtube.com/embed/videoseries?list=${video.playlistId}`
  }
  return `https://www.youtube.com/embed/${video.youtubeId}`
}

const PROGRESS_KEY = 'ats_agentic_video_done'

export function loadVideoProgress(): Set<string> {
  try {
    const raw = localStorage.getItem(PROGRESS_KEY)
    if (!raw) return new Set()
    return new Set(JSON.parse(raw) as string[])
  } catch {
    return new Set()
  }
}

export function saveVideoProgress(done: Set<string>) {
  localStorage.setItem(PROGRESS_KEY, JSON.stringify([...done]))
}
