import type { Feedback, Track, TrackId, TutorQuestion } from './api'

export const TRACKS: Track[] = [
  {
    id: "staff-interview",
    title: "Staff Engineer Interview Prep",
    audience: "Senior / Staff IC candidates",
    summary: "System design, ownership stories, and production AI depth for Staff loops.",
    outcomes: [
      "Tell Staff-level ownership stories with metrics",
      "Design distributed systems with clear tradeoffs",
      "Explain production AI guardrails (entitlements, audit, evals)",
      "Narrate influence and incident leadership under pressure",
      "Frame technical strategy and ambiguous problem solving",
    ],
    study_plan: [
      "Day 1–2: Ownership + mentoring stories (Context → Action → Metric)",
      "Day 3–4: System design drills (sync engine + public API platform)",
      "Day 5: Influence + ambiguous problem framing",
      "Day 6: Incidents + safe enterprise AI narrative",
      "Day 7–8: Full mock loop out loud — score ≥4 on every topic",
    ],
  },
  {
    id: "em-interview",
    title: "Engineering Manager Interview Prep",
    audience: "EM / player-coach leaders",
    summary: "People leadership, delivery, hiring, and vendor/team-build narratives.",
    outcomes: [
      "Lead with people + delivery ownership, not only IC craft",
      "Run hiring / performance / incident stories cleanly",
      "Show technical credibility without competing for IC tickets",
      "Prioritize roadmap vs reliability with clear options",
      "Communicate up to execs and design healthy org shapes",
    ],
    study_plan: [
      "Day 1: Memorize 30–40s EM opener",
      "Day 2–3: Team-from-scratch + vendor-to-in-house STAR cards",
      "Day 4: Hiring bar + performance management scenarios",
      "Day 5: Delivery / prioritization + exec communication",
      "Day 6: Org design / span of control",
      "Day 7–8: Mock HM screen — speak every topic until score ≥4",
    ],
  },
  {
    id: "java-to-ai",
    title: "Java → Production AI Upskilling",
    audience: "Java/backend engineers moving into AI",
    summary: "Practical path from Spring services to RAG, agents, and safe LLM features.",
    outcomes: [
      "Map Spring concepts to FastAPI / AI service patterns",
      "Explain RAG vs fine-tuning vs prompt-only clearly",
      "Design an entitlement-safe NLQ or document pipeline",
      "Define evals, cost controls, and production failure modes",
    ],
    study_plan: [
      "Week 1: Python fluency + HTTP/LLM basics",
      "Week 2: RAG building blocks (chunk, embed, retrieve, cite)",
      "Week 3: Agents/tools + guardrails + evals",
      "Week 4: Cost, latency, and production ops for LLM features",
      "Week 5: Ship a tiny production-shaped AI feature + speak the design",
    ],
  },
  {
    id: 'java-to-python',
    title: 'Java → Python Developer',
    audience: 'Java engineers switching to Python',
    summary:
      'Map Java/Spring instincts to Python: syntax, typing, OOP, asyncio, and FastAPI.',
    outcomes: [
      'Translate Java types and collections into idiomatic Python',
      'Use typing, venv/packaging, and pytest like a production Python engineer',
      'Explain Spring concepts as FastAPI + Pydantic equivalents',
    ],
    study_plan: [
      'Day 1–2: Syntax & collections map (list/dict/set, comprehensions)',
      'Day 3: Classes, dataclasses, protocols vs Java interfaces',
      'Day 4: Typing (mypy) + packaging (venv/poetry) + pytest',
      'Day 5: asyncio vs executors; when to use each',
      'Day 6–7: Rebuild a small Spring-style API in FastAPI and practice explaining it',
    ],
  },
  {
    id: 'java',
    title: 'Java',
    audience: 'Backend / JVM engineers',
    summary: 'Core Java, concurrency, Spring Boot, and production service patterns.',
    outcomes: [
      'Explain OOP, collections, and concurrency clearly',
      'Design Spring Boot APIs with solid error handling',
      'Talk JVM memory, threads, and performance tradeoffs',
    ],
    study_plan: [
      'Day 1–2: OOP, equals/hashCode, collections, generics',
      'Day 3–4: Threads, executors, CompletableFuture',
      'Day 5: Spring Boot REST, validation, transactions',
      'Day 6–7: Practice debugging and production failure scenarios',
    ],
  },
  {
    id: 'python',
    title: 'Python',
    audience: 'Backend / scripting / AI-adjacent',
    summary: 'Python fundamentals, typing, async, and packaging for real services.',
    outcomes: [
      'Write clean typed Python with clear module structure',
      'Explain GIL, async/await, and when to use each',
      'Build FastAPI-style request/response flows',
    ],
    study_plan: [
      'Day 1–2: Data structures, comprehensions, typing',
      'Day 3: OOP, dataclasses, protocols',
      'Day 4–5: Async IO + HTTP clients',
      'Day 6–7: Packaging, testing, FastAPI basics',
    ],
  },
  {
    id: 'javascript',
    title: 'JavaScript',
    audience: 'Web / fullstack beginners → mid',
    summary: 'Modern JS: language essentials, async, DOM, and browser APIs.',
    outcomes: [
      'Master closures, prototypes, and this-binding',
      'Use promises/async-await confidently',
      'Manipulate the DOM and handle events cleanly',
    ],
    study_plan: [
      'Day 1–2: Types, scope, hoisting, closures',
      'Day 3: Arrays/objects + functional helpers',
      'Day 4–5: Promises, async/await, fetch',
      'Day 6–7: DOM events and small UI scripts',
    ],
  },
  {
    id: 'typescript',
    title: 'TypeScript',
    audience: 'JS developers leveling up',
    summary: 'Types, generics, utility types, and typing React/Node apps.',
    outcomes: [
      'Model domain data with interfaces and unions',
      'Use generics and utility types effectively',
      'Type API responses and component props safely',
    ],
    study_plan: [
      'Day 1–2: Primitives, unions, narrowing',
      'Day 3: Interfaces vs types, generics',
      'Day 4: Utility types + mapped types',
      'Day 5–7: Type a small React + API client',
    ],
  },
  {
    id: 'react',
    title: 'React',
    audience: 'Frontend engineers',
    summary: 'Components, hooks, state, effects, and production React patterns.',
    outcomes: [
      'Build components with clean props and state',
      'Use effects correctly without common bugs',
      'Explain rendering, keys, and performance basics',
    ],
    study_plan: [
      'Day 1–2: Components, props, state, lists/keys',
      'Day 3–4: useEffect, data fetching, cleanup',
      'Day 5: Context + lifting state',
      'Day 6–7: Forms, errors, and a mini feature',
    ],
  },
  {
    id: 'nodejs',
    title: 'Node.js',
    audience: 'Backend / fullstack JS',
    summary: 'Node runtime, Express/Fastify APIs, async I/O, and packaging.',
    outcomes: [
      'Explain event loop and non-blocking I/O',
      'Build REST APIs with middleware and validation',
      'Handle errors, env config, and basic security',
    ],
    study_plan: [
      'Day 1–2: Modules, npm, event loop basics',
      'Day 3–4: HTTP servers + Express routes',
      'Day 5: Auth/JWT overview + validation',
      'Day 6–7: Logging, errors, deploy checklist',
    ],
  },
  {
    id: 'html',
    title: 'HTML',
    audience: 'Web fundamentals',
    summary: 'Semantic HTML, forms, accessibility, and document structure.',
    outcomes: [
      'Use semantic tags for structure and SEO',
      'Build accessible forms and navigation',
      'Understand HTML5 APIs at a practical level',
    ],
    study_plan: [
      'Day 1: Document structure + semantic landmarks',
      'Day 2–3: Forms, inputs, validation attributes',
      'Day 4: Media, tables, metadata',
      'Day 5–7: Accessibility checklist + rebuild a landing section',
    ],
  },
  {
    id: 'css',
    title: 'CSS',
    audience: 'Web fundamentals / UI',
    summary: 'Layout, flex/grid, responsive design, and modern styling patterns.',
    outcomes: [
      'Build layouts with Flexbox and Grid',
      'Make responsive UIs with media queries',
      'Use variables, specificity, and clean organization',
    ],
    study_plan: [
      'Day 1–2: Cascade, specificity, box model',
      'Day 3–4: Flexbox + Grid layouts',
      'Day 5: Responsive design + typography',
      'Day 6–7: Recreate a card/hero section pixel-clean',
    ],
  },
]

export const QUESTIONS: TutorQuestion[] = [
  {
    id: "staff-ownership",
    track_id: "staff-interview",
    topic_id: "staff-stories",
    category: "Behavioral",
    prompt: "Tell me about a system you owned end-to-end. What was hard, what did you decide, and what measurable outcome did you drive?",
    hints: [
      "Lead with scope and users",
      "Name 1–2 hard tradeoffs",
      "End with a metric (uptime, latency, manual hours saved)",
    ],
    strong_answer_signals: [
      "owned",
      "tradeoff",
      "metric",
      "production",
      "reliability",
      "customer",
    ],
  },
  {
    id: "staff-design-sync",
    track_id: "staff-interview",
    topic_id: "staff-design",
    category: "System design",
    prompt: "Design a customer data syncing engine that must move large volumes of data to destinations reliably. How would you approach batch today and streaming later?",
    hints: [
      "Separate ingest, transform, deliver, observe",
      "Talk retries, idempotency, backpressure",
      "Call out multi-tenant isolation and failure modes",
    ],
    strong_answer_signals: [
      "idempotent",
      "retry",
      "queue",
      "batch",
      "stream",
      "observability",
      "backpressure",
    ],
  },
  {
    id: "staff-ai-guardrails",
    track_id: "staff-interview",
    topic_id: "staff-ai-safe",
    category: "AI / production",
    prompt: "How would you ship an enterprise natural-language-to-SQL feature safely when different customers must never see each other's data?",
    hints: [
      "Entitlements before model call",
      "Fail-closed validation on generated SQL",
      "Audit + rate limits + eval set",
    ],
    strong_answer_signals: [
      "entitlement",
      "guardrail",
      "fail-closed",
      "audit",
      "rate limit",
      "eval",
    ],
  },
  {
    id: "staff-influence",
    track_id: "staff-interview",
    topic_id: "staff-influence",
    category: "Behavioral",
    prompt: "Tell me about a time you influenced a technical decision across teams without formal authority. What was the disagreement, how did you get alignment, and what shipped?",
    hints: [
      "State the decision and who disagreed",
      "Show data / prototype / risk framing — not politics",
      "End with what changed and the business outcome",
    ],
    strong_answer_signals: [
      "influence",
      "alignment",
      "tradeoff",
      "stakeholder",
      "prototype",
      "decision",
      "shipped",
    ],
  },
  {
    id: "staff-api-tradeoff",
    track_id: "staff-interview",
    topic_id: "staff-design",
    category: "System design",
    prompt: "You need a public API used by multiple product teams. How do you design versioning, auth, rate limits, and backwards compatibility so the platform can evolve without breaking clients?",
    hints: [
      "Separate public contracts from internal models",
      "Talk versioning strategy and deprecation windows",
      "Cover authn/authz, quotas, and observability per tenant",
    ],
    strong_answer_signals: [
      "version",
      "compatibility",
      "auth",
      "rate limit",
      "deprecat",
      "contract",
      "tenant",
      "observability",
    ],
  },
  {
    id: "staff-incident",
    track_id: "staff-interview",
    topic_id: "staff-incidents",
    category: "Production",
    prompt: "Walk me through a production incident you led or heavily influenced. How did you diagnose, mitigate, communicate, and prevent recurrence?",
    hints: [
      "Timeline: detect → mitigate → communicate → root cause → follow-ups",
      "Distinguish customer impact vs internal noise",
      "Name a lasting fix (alert, runbook, code, process)",
    ],
    strong_answer_signals: [
      "incident",
      "mitigate",
      "root cause",
      "customer",
      "communicat",
      "postmortem",
      "alert",
      "prevent",
    ],
  },
  {
    id: "staff-mentor",
    track_id: "staff-interview",
    topic_id: "staff-stories",
    category: "Behavioral",
    prompt: "Describe how you raised the engineering bar for others — mentoring, design reviews, or standards — while still delivering your own Staff-level work.",
    hints: [
      "Concrete before/after for a person or team practice",
      "How you balanced delivery with coaching time",
      "Evidence the bar actually rose (quality, speed, fewer incidents)",
    ],
    strong_answer_signals: [
      "mentor",
      "review",
      "standard",
      "coaching",
      "quality",
      "bar",
      "delivery",
    ],
  },
  {
    id: "staff-ambiguity",
    track_id: "staff-interview",
    topic_id: "staff-ambiguity",
    category: "Problem solving",
    prompt: "You're given a vague product request: 'make search smarter with AI.' How do you turn that into a Staff-level plan in the first two weeks — and what do you refuse to build yet?",
    hints: [
      "Clarify users, success metric, and constraints before architecture",
      "Propose a thin vertical slice + kill criteria",
      "Call out risks: data quality, entitlements, cost, evals",
    ],
    strong_answer_signals: [
      "clarify",
      "metric",
      "constraint",
      "slice",
      "risk",
      "eval",
      "entitle",
      "cost",
      "refuse",
    ],
  },
  {
    id: "staff-strategy",
    track_id: "staff-interview",
    topic_id: "staff-strategy",
    category: "Technical strategy",
    prompt: "Your org has three overlapping data platforms and rising ops cost. How would you drive a multi-quarter technical strategy without a formal VP title?",
    hints: [
      "Current-state pain with numbers",
      "North-star architecture + migration stages",
      "Coalition: who must buy in and how you sequence wins",
    ],
    strong_answer_signals: [
      "strategy",
      "migrat",
      "cost",
      "roadmap",
      "stakeholder",
      "north",
      "sequen",
      "platform",
      "win",
    ],
  },
  {
    id: "em-opener",
    track_id: "em-interview",
    topic_id: "em-people",
    category: "Leadership",
    prompt: "Give your 30–40 second introduction as an Engineering Manager. Include scope, signature wins, and what you're looking for next.",
    hints: [
      "Lead with people ownership",
      "Mention team size / footprint",
      "One transformation win + one AI/product win",
    ],
    strong_answer_signals: [
      "team",
      "hiring",
      "delivery",
      "coaching",
      "uptime",
      "product",
    ],
  },
  {
    id: "em-vendor",
    track_id: "em-interview",
    topic_id: "em-transform",
    category: "Transformation",
    prompt: "Describe leading a vendor-to-in-house transition. How did you protect delivery and uptime while building the team?",
    hints: [
      "Continuity plan first",
      "Hiring + knowledge transfer",
      "Explicit uptime / customer impact metric",
    ],
    strong_answer_signals: [
      "vendor",
      "in-house",
      "hiring",
      "uptime",
      "knowledge transfer",
      "stakeholder",
    ],
  },
  {
    id: "em-conflict",
    track_id: "em-interview",
    topic_id: "em-people",
    category: "People",
    prompt: "Product wants more features; your team is drowning in reliability work. How do you handle the conflict?",
    hints: [
      "Reframe to shared outcomes",
      "Bring options with risk",
      "Escalate only with a recommendation",
    ],
    strong_answer_signals: [
      "tradeoff",
      "risk",
      "capacity",
      "roadmap",
      "option",
      "reliability",
    ],
  },
  {
    id: "em-hiring-bar",
    track_id: "em-interview",
    topic_id: "em-hiring",
    category: "Hiring",
    prompt: "How do you run a hiring loop and keep the bar high when the team is under delivery pressure to 'just hire someone'?",
    hints: [
      "Define the bar for the level before interviews",
      "Structured signals + debrief discipline",
      "What you do when stakeholders push to lower the bar",
    ],
    strong_answer_signals: [
      "hiring",
      "bar",
      "loop",
      "debrief",
      "level",
      "signal",
      "reject",
      "stakeholder",
    ],
  },
  {
    id: "em-performance",
    track_id: "em-interview",
    topic_id: "em-people",
    category: "People",
    prompt: "Tell me about managing an underperformer. How did you diagnose, coach, document, and decide whether to exit or recover?",
    hints: [
      "Early, specific feedback with examples",
      "Written plan + support, not surprise PIP",
      "Fairness to the person and to the team",
    ],
    strong_answer_signals: [
      "performance",
      "feedback",
      "coach",
      "document",
      "plan",
      "exit",
      "fair",
      "team",
    ],
  },
  {
    id: "em-roadmap",
    track_id: "em-interview",
    topic_id: "em-delivery",
    category: "Delivery",
    prompt: "How do you build a quarterly roadmap with product when engineering capacity is constrained and reliability work is non-negotiable?",
    hints: [
      "Make capacity and commitments visible",
      "Offer explicit options (cut scope / slip / add capacity)",
      "Protect a reliability / quality budget",
    ],
    strong_answer_signals: [
      "roadmap",
      "capacity",
      "priorit",
      "reliab",
      "option",
      "commit",
      "scope",
      "stakeholder",
    ],
  },
  {
    id: "em-exec",
    track_id: "em-interview",
    topic_id: "em-exec",
    category: "Exec communication",
    prompt: "Your VP asks why a major initiative is late. How do you communicate status, options, and a recommendation in under three minutes?",
    hints: [
      "Lead with customer/business impact, not task lists",
      "Give 2–3 options with cost/risk",
      "End with a clear ask or decision",
    ],
    strong_answer_signals: [
      "impact",
      "option",
      "risk",
      "recommend",
      "ask",
      "timeline",
      "capacity",
      "customer",
    ],
  },
  {
    id: "em-org",
    track_id: "em-interview",
    topic_id: "em-org",
    category: "Org design",
    prompt: "A team of 18 reports to you and delivery is slowing. How do you rethink org shape, ownership boundaries, and manager span without creating chaos?",
    hints: [
      "Diagnose bottleneck: meetings, unclear ownership, or skill mix",
      "Propose team splits with clear missions",
      "Transition plan for people and systems",
    ],
    strong_answer_signals: [
      "ownership",
      "span",
      "mission",
      "split",
      "boundary",
      "transition",
      "delivery",
      "manager",
    ],
  },
  {
    id: "em-incident-leadership",
    track_id: "em-interview",
    topic_id: "em-delivery",
    category: "Delivery",
    prompt: "A SEV is ongoing. How do you lead as EM — who does what, how do you protect the team, and what do you tell stakeholders?",
    hints: [
      "Separate incident commander vs EM communication role",
      "Protect deep work; rotate; no blame during mitigate",
      "Stakeholder updates with ETA and customer impact",
    ],
    strong_answer_signals: [
      "incident",
      "commander",
      "stakeholder",
      "customer",
      "protect",
      "rotate",
      "update",
      "postmortem",
    ],
  },
  {
    id: "java-ai-map",
    track_id: "java-to-ai",
    topic_id: "ai-path",
    category: "Concepts",
    prompt: "You're a Java/Spring engineer. Explain how you would structure a production AI feature service and what maps from Spring Boot patterns.",
    hints: [
      "Controllers → API routes",
      "Services → orchestration + tools",
      "Observability and config still matter",
    ],
    strong_answer_signals: [
      "spring",
      "api",
      "service",
      "observability",
      "config",
      "timeout",
      "retry",
    ],
  },
  {
    id: "java-rag",
    track_id: "java-to-ai",
    topic_id: "ai-rag",
    category: "RAG",
    prompt: "When would you use RAG instead of fine-tuning, and how would you evaluate whether retrieval quality is good enough?",
    hints: [
      "Fresh / private knowledge → RAG",
      "Behavior/style → maybe fine-tune",
      "Eval with golden questions + citation checks",
    ],
    strong_answer_signals: [
      "rag",
      "fine-tune",
      "retrieval",
      "citation",
      "eval",
      "chunk",
    ],
  },
  {
    id: "java-agents",
    track_id: "java-to-ai",
    topic_id: "ai-agents",
    category: "Agents",
    prompt: "Design a simple document extraction agent for messy Excel/PDF inputs. What steps, tools, and failure handling do you need?",
    hints: [
      "Ingest → extract → validate → retry → store",
      "Deterministic validation gates",
      "Human review on low confidence",
    ],
    strong_answer_signals: [
      "validate",
      "retry",
      "tool",
      "confidence",
      "pipeline",
      "human",
    ],
  },
  {
    id: "java-ai-evals",
    track_id: "java-to-ai",
    topic_id: "ai-evals",
    category: "Evals",
    prompt: "How would you build an evaluation harness for an LLM feature before and after shipping — and what gates would stop a bad model deploy?",
    hints: [
      "Golden set + regression suite",
      "Offline metrics vs online shadow traffic",
      "Fail closed on safety/entitlement regressions",
    ],
    strong_answer_signals: [
      "eval",
      "golden",
      "regress",
      "shadow",
      "metric",
      "gate",
      "safety",
      "deploy",
    ],
  },
  {
    id: "java-ai-ops",
    track_id: "java-to-ai",
    topic_id: "ai-ops",
    category: "Production",
    prompt: "An LLM feature is slow and expensive in production. How do you diagnose and improve latency and cost without wrecking answer quality?",
    hints: [
      "Measure token use, cache hits, retrieval size",
      "Prompt/model routing, caching, batching",
      "Quality guardrails so cuts don’t silently degrade",
    ],
    strong_answer_signals: [
      "latency",
      "cost",
      "token",
      "cache",
      "routing",
      "quality",
      "observ",
      "retriev",
    ],
  },
  {
    id: "java-oop",
    track_id: "java",
    topic_id: "java-oop",
    category: "Fundamentals",
    prompt: "Explain encapsulation, inheritance, and polymorphism with a realistic Spring service example.",
    hints: [
      "Prefer composition when inheritance gets messy",
      "Show interface + implementation",
      "Mention testability",
    ],
    strong_answer_signals: [
      "interface",
      "encapsulation",
      "polymorphism",
      "inheritance",
      "spring",
      "test",
    ],
  },
  {
    id: "java-concurrency",
    track_id: "java",
    topic_id: "java-concurrency",
    category: "Concurrency",
    prompt: "How would you parallelize independent I/O-bound tasks in Java without blocking the request thread carelessly?",
    hints: [
      "ExecutorService / CompletableFuture",
      "Timeouts and cancellation",
      "Backpressure / bounded pools",
    ],
    strong_answer_signals: [
      "executor",
      "completablefuture",
      "timeout",
      "thread",
      "pool",
      "async",
    ],
  },
  {
    id: "java-spring-api",
    track_id: "java",
    topic_id: "java-spring",
    category: "Spring Boot",
    prompt: "Design a Spring Boot REST endpoint that validates input, calls a service, and returns consistent error responses.",
    hints: [
      "Controller → Service separation",
      "@Valid + problem details",
      "Transaction boundaries",
    ],
    strong_answer_signals: [
      "controller",
      "service",
      "validation",
      "exception",
      "dto",
      "transaction",
    ],
  },
  {
    id: "python-typing",
    track_id: "python",
    topic_id: "python-basics",
    category: "Fundamentals",
    prompt: "Why use type hints in Python services, and how do dataclasses/pydantic help API boundaries?",
    hints: [
      "Catch bugs earlier",
      "Better editor support",
      "Validate request/response shapes",
    ],
    strong_answer_signals: [
      "typing",
      "dataclass",
      "pydantic",
      "validation",
      "mypy",
      "api",
    ],
  },
  {
    id: "python-async",
    track_id: "python",
    topic_id: "python-async",
    category: "Async",
    prompt: "When should you use asyncio in Python, and what mistakes do people make with blocking calls inside async functions?",
    hints: [
      "I/O-bound concurrency",
      "Do not block the event loop",
      "Use thread/process offload for CPU",
    ],
    strong_answer_signals: [
      "asyncio",
      "await",
      "event loop",
      "blocking",
      "io",
      "concurrent",
    ],
  },
  {
    id: "python-fastapi",
    track_id: "python",
    topic_id: "python-fastapi",
    category: "APIs",
    prompt: "Sketch a FastAPI endpoint that accepts JSON, validates it, and returns a typed response model.",
    hints: [
      "Pydantic models",
      "Dependency injection",
      "HTTPException for errors",
    ],
    strong_answer_signals: [
      "fastapi",
      "pydantic",
      "response",
      "dependency",
      "validation",
      "httpexception",
    ],
  },
  {
    id: "js-closures",
    track_id: "javascript",
    topic_id: "js-language",
    category: "Language",
    prompt: "Explain closures with a practical example (e.g. private counters or event handlers).",
    hints: [
      "Function remembers outer scope",
      "Useful for encapsulation",
      "Watch accidental loop captures",
    ],
    strong_answer_signals: [
      "closure",
      "scope",
      "lexical",
      "function",
      "private",
      "callback",
    ],
  },
  {
    id: "js-async",
    track_id: "javascript",
    topic_id: "js-async",
    category: "Async",
    prompt: "Compare callbacks, promises, and async/await. When does Promise.all matter?",
    hints: [
      "Error handling differences",
      "Parallel vs sequential awaits",
      "Promise.allSettled for partial failure",
    ],
    strong_answer_signals: [
      "promise",
      "async",
      "await",
      "callback",
      "promise.all",
      "error",
    ],
  },
  {
    id: "js-dom",
    track_id: "javascript",
    topic_id: "js-dom",
    category: "DOM",
    prompt: "How would you build a small interactive UI (toggle + list render) with vanilla JS and event delegation?",
    hints: [
      "querySelector / createElement",
      "addEventListener",
      "Delegate from parent for dynamic lists",
    ],
    strong_answer_signals: [
      "dom",
      "event",
      "delegation",
      "queryselector",
      "listener",
      "render",
    ],
  },
  {
    id: "ts-unions",
    track_id: "typescript",
    topic_id: "ts-basics",
    category: "Types",
    prompt: "Explain union types and type narrowing with an example of API success vs error responses.",
    hints: [
      "Discriminated unions",
      "in / typeof / switch",
      "Exhaustiveness checks",
    ],
    strong_answer_signals: [
      "union",
      "narrowing",
      "discriminated",
      "typeof",
      "interface",
      "exhaustive",
    ],
  },
  {
    id: "ts-generics",
    track_id: "typescript",
    topic_id: "ts-generics",
    category: "Generics",
    prompt: "Write (in words or pseudocode) a generic fetchJson<T>() helper and explain the type parameter.",
    hints: [
      "Return Promise<T>",
      "Caller chooses T",
      "Validate at runtime separately if needed",
    ],
    strong_answer_signals: [
      "generic",
      "promise",
      "type parameter",
      "fetch",
      "json",
      "reuse",
    ],
  },
  {
    id: "ts-react-props",
    track_id: "typescript",
    topic_id: "ts-react",
    category: "React + TS",
    prompt: "How do you type React props and state for a form component with optional fields?",
    hints: [
      "Props interface",
      "useState<Type>",
      "Partial / required utilities",
    ],
    strong_answer_signals: [
      "props",
      "interface",
      "usestate",
      "optional",
      "component",
      "type",
    ],
  },
  {
    id: "react-state",
    track_id: "react",
    topic_id: "react-components",
    category: "State",
    prompt: "When do you lift state up vs keep it local? Give a concrete UI example.",
    hints: [
      "Share only what siblings need",
      "Avoid prop drilling with context carefully",
      "Keep ephemeral UI state local",
    ],
    strong_answer_signals: [
      "state",
      "lift",
      "props",
      "parent",
      "context",
      "local",
    ],
  },
  {
    id: "react-effects",
    track_id: "react",
    topic_id: "react-effects",
    category: "Hooks",
    prompt: "What are common useEffect mistakes, and how do you fetch data safely in React?",
    hints: [
      "Dependency arrays",
      "Cleanup / abort controllers",
      "Prefer frameworks or query libs for caching",
    ],
    strong_answer_signals: [
      "useeffect",
      "dependency",
      "cleanup",
      "abort",
      "fetch",
      "race",
    ],
  },
  {
    id: "react-keys",
    track_id: "react",
    topic_id: "react-lists",
    category: "Rendering",
    prompt: "Why are keys important in lists, and what goes wrong if you use array index as key during reordering?",
    hints: [
      "Identity across renders",
      "State can attach to wrong item",
      "Stable ids from data",
    ],
    strong_answer_signals: [
      "key",
      "list",
      "identity",
      "index",
      "reorder",
      "state",
    ],
  },
  {
    id: "node-eventloop",
    track_id: "nodejs",
    topic_id: "node-runtime",
    category: "Runtime",
    prompt: "Explain the Node.js event loop in practical terms. What happens if you run CPU-heavy work on the main thread?",
    hints: [
      "Non-blocking I/O",
      "Phases at a high level",
      "Offload CPU to worker threads",
    ],
    strong_answer_signals: [
      "event loop",
      "non-blocking",
      "io",
      "cpu",
      "worker",
      "async",
    ],
  },
  {
    id: "node-express",
    track_id: "nodejs",
    topic_id: "node-apis",
    category: "APIs",
    prompt: "Design an Express (or similar) REST API with middleware for logging, auth, and centralized error handling.",
    hints: [
      "Router + middleware chain",
      "next(err) pattern",
      "Validate body/query",
    ],
    strong_answer_signals: [
      "express",
      "middleware",
      "router",
      "auth",
      "error",
      "validation",
    ],
  },
  {
    id: "node-security",
    track_id: "nodejs",
    topic_id: "node-prod",
    category: "Production",
    prompt: "List practical security basics for a Node API in production (secrets, headers, input, deps).",
    hints: [
      "Env secrets, not hardcoding",
      "Helmet / CORS awareness",
      "Dependency audits",
    ],
    strong_answer_signals: [
      "secret",
      "env",
      "helmet",
      "cors",
      "validation",
      "dependency",
    ],
  },
  {
    id: "html-semantic",
    track_id: "html",
    topic_id: "html-semantic",
    category: "Semantics",
    prompt: "Why does semantic HTML matter for accessibility and SEO? Give tag examples for a blog post page.",
    hints: [
      "header/nav/main/article/footer",
      "Screen readers",
      "Meaningful structure",
    ],
    strong_answer_signals: [
      "semantic",
      "accessibility",
      "seo",
      "article",
      "nav",
      "main",
    ],
  },
  {
    id: "html-forms",
    track_id: "html",
    topic_id: "html-forms",
    category: "Forms",
    prompt: "Build (describe) an accessible signup form with labels, required fields, and useful input types.",
    hints: [
      "label for= / wrapping",
      "type=email password",
      "required + autocomplete",
    ],
    strong_answer_signals: [
      "label",
      "input",
      "required",
      "accessible",
      "type",
      "form",
    ],
  },
  {
    id: "html-a11y",
    track_id: "html",
    topic_id: "html-a11y",
    category: "Accessibility",
    prompt: "What are 5 HTML accessibility checks you would run before shipping a marketing page?",
    hints: [
      "Alt text",
      "Keyboard focus",
      "Color is not the only signal",
      "Landmarks/headings",
    ],
    strong_answer_signals: [
      "alt",
      "keyboard",
      "aria",
      "contrast",
      "heading",
      "focus",
    ],
  },
  {
    id: "css-box",
    track_id: "css",
    topic_id: "css-box",
    category: "Fundamentals",
    prompt: "Explain the box model and how box-sizing: border-box changes layout math.",
    hints: [
      "content + padding + border",
      "margin collapse awareness",
      "border-box includes padding/border in width",
    ],
    strong_answer_signals: [
      "box model",
      "padding",
      "border",
      "margin",
      "border-box",
      "width",
    ],
  },
  {
    id: "css-flexgrid",
    track_id: "css",
    topic_id: "css-layout",
    category: "Layout",
    prompt: "When do you choose Flexbox vs Grid? Describe a header + card gallery layout.",
    hints: [
      "Flex for 1D alignment",
      "Grid for 2D page areas",
      "Can combine both",
    ],
    strong_answer_signals: [
      "flexbox",
      "grid",
      "layout",
      "responsive",
      "header",
      "cards",
    ],
  },
  {
    id: "css-responsive",
    track_id: "css",
    topic_id: "css-responsive",
    category: "Responsive",
    prompt: "How would you make a page responsive using relative units and media queries without breaking desktop layout?",
    hints: [
      "Mobile-first media queries",
      "rem/em/%/clamp",
      "Test common breakpoints",
    ],
    strong_answer_signals: [
      "media query",
      "responsive",
      "rem",
      "breakpoint",
      "mobile-first",
      "clamp",
    ],
  },
  {
    id: "j2p-mindset-q",
    track_id: "java-to-python",
    topic_id: "j2p-mindset",
    category: "Transition",
    prompt: "You are a Java engineer moving to Python. What skills transfer, what do you unlearn, and how do you stay production-safe without Java’s ceremony?",
    hints: [
      "Keep systems / API / testing instincts",
      "Unlearn mandatory classes and getters everywhere",
      "Mention typing + venv + tests as the safety net",
    ],
    strong_answer_signals: [
      "transfer",
      "unlearn",
      "typing",
      "venv",
      "idiomatic",
      "production",
    ],
  },
  {
    id: "j2p-syntax-q",
    track_id: "java-to-python",
    topic_id: "j2p-syntax",
    category: "Language",
    prompt: "Map Java List and Map to Python. When do you use a comprehension, and what mutable-default pitfall must you avoid?",
    hints: [
      "list/dict/set mapping",
      "comprehension for transforms",
      "never def f(xs=[])",
    ],
    strong_answer_signals: [
      "list",
      "dict",
      "comprehension",
      "mutable default",
      "set",
      "tuple",
    ],
  },
  {
    id: "j2p-oop-q",
    track_id: "java-to-python",
    topic_id: "j2p-oop",
    category: "OOP",
    prompt: "How do Python dataclasses and Protocol compare to Java records/Lombok and interfaces? When do you still write a full class?",
    hints: [
      "dataclass for data carriers",
      "Protocol = structural typing",
      "full class when behavior/invariants matter",
    ],
    strong_answer_signals: [
      "dataclass",
      "protocol",
      "interface",
      "composition",
      "invariant",
      "property",
    ],
  },
  {
    id: "j2p-typing-q",
    track_id: "java-to-python",
    topic_id: "j2p-typing",
    category: "Tooling",
    prompt: "Describe the Python toolchain you would require on a team coming from Maven/JUnit: environments, types, tests, and CI checks.",
    hints: [
      "venv or poetry/uv",
      "mypy/pyright",
      "pytest",
      "ruff/black in CI",
    ],
    strong_answer_signals: [
      "venv",
      "mypy",
      "pytest",
      "ci",
      "poetry",
      "type hint",
    ],
  },
  {
    id: "j2p-async-q",
    track_id: "java-to-python",
    topic_id: "j2p-async",
    category: "Concurrency",
    prompt: "Compare Java ExecutorService / CompletableFuture to Python asyncio. When is asyncio the wrong tool?",
    hints: [
      "I/O bound vs CPU bound",
      "do not block the event loop",
      "process pool for CPU",
    ],
    strong_answer_signals: [
      "asyncio",
      "event loop",
      "i/o",
      "cpu",
      "blocking",
      "gather",
    ],
  },
  {
    id: "j2p-fastapi-q",
    track_id: "java-to-python",
    topic_id: "j2p-fastapi",
    category: "APIs",
    prompt: "Explain Spring Boot REST + Bean Validation as FastAPI + Pydantic. Where does business logic live, and what do you keep identical to Java service design?",
    hints: [
      "Pydantic ≈ @Valid DTOs",
      "thin routes, fat services",
      "OpenAPI docs parallel",
    ],
    strong_answer_signals: [
      "fastapi",
      "pydantic",
      "validation",
      "service",
      "openapi",
      "dependency",
    ],
  },
  {
    id: "staff-cross-team",
    track_id: "staff-interview",
    topic_id: "staff-influence",
    category: "Behavioral",
    prompt: "Describe a time you aligned two teams with conflicting priorities. How did you get to a decision without formal authority?",
    hints: [
      "Name the conflict in one sentence",
      "Explain how you framed shared outcomes",
      "End with what changed in behavior or delivery",
    ],
    strong_answer_signals: [
      "align",
      "stakeholders",
      "tradeoff",
      "shared goal",
      "influence",
      "decision",
    ],
  },
  {
    id: "staff-tech-debt",
    track_id: "staff-interview",
    topic_id: "staff-strategy",
    category: "Technical strategy",
    prompt: "How do you decide when to pay down tech debt versus ship features? Give a concrete example.",
    hints: [
      "State the business risk of the debt",
      "Compare cost of delay vs rewrite",
      "Share the sequencing you chose",
    ],
    strong_answer_signals: [
      "tech debt",
      "risk",
      "sequencing",
      "ROI",
      "migration",
      "reliability",
    ],
  },
  {
    id: "staff-design-review",
    track_id: "staff-interview",
    topic_id: "staff-design",
    category: "System design",
    prompt: "Walk me through a design review you ran. What did you push back on, and what did you accept?",
    hints: [
      "Clarify requirements and constraints",
      "Call out the risky assumption",
      "Say what you deferred and why",
    ],
    strong_answer_signals: [
      "design review",
      "constraint",
      "assumption",
      "tradeoff",
      "scalability",
      "API",
    ],
  },
  {
    id: "staff-oncall-story",
    track_id: "staff-interview",
    topic_id: "staff-incidents",
    category: "Incidents",
    prompt: "Tell me about an on-call incident where you improved the system afterward, not just restored service.",
    hints: [
      "Timeline: detect → mitigate → recover",
      "Root cause without blame",
      "Permanent fix + prevention",
    ],
    strong_answer_signals: [
      "incident",
      "mitigate",
      "root cause",
      "runbook",
      "monitoring",
      "postmortem",
    ],
  },
  {
    id: "staff-ai-prod",
    track_id: "staff-interview",
    topic_id: "staff-ai-safe",
    category: "AI safety",
    prompt: "How would you put guardrails around an LLM feature in a production product used by customers?",
    hints: [
      "Threat model: leakage, hallucinations, abuse",
      "Evaluation and human review gates",
      "Rollback and cost controls",
    ],
    strong_answer_signals: [
      "guardrail",
      "eval",
      "hallucination",
      "PII",
      "rate limit",
      "rollback",
    ],
  },
  {
    id: "staff-ambiguous-scope",
    track_id: "staff-interview",
    topic_id: "staff-ambiguity",
    category: "Ambiguity",
    prompt: "A PM asks for “AI search” with no requirements. How do you create a Staff-level plan in the first week?",
    hints: [
      "Clarify users and success metrics",
      "Spike options with costs",
      "Propose a thin vertical slice",
    ],
    strong_answer_signals: [
      "clarify",
      "metric",
      "spike",
      "MVP",
      "users",
      "scope",
    ],
  },
  {
    id: "staff-mentorship-impact",
    track_id: "staff-interview",
    topic_id: "staff-stories",
    category: "Behavioral",
    prompt: "Tell me about mentoring someone who leveled up because of your coaching. What did you do differently?",
    hints: [
      "Start with their goal",
      "Your concrete coaching loop",
      "Evidence they grew",
    ],
    strong_answer_signals: [
      "mentor",
      "feedback",
      "growth",
      "ownership",
      "coach",
      "outcome",
    ],
  },
  {
    id: "em-1on1-hard",
    track_id: "em-interview",
    topic_id: "em-people",
    category: "People",
    prompt: "How do you run a 1:1 when someone is underperforming but still valuable? Walk through a real example.",
    hints: [
      "Separate behavior from identity",
      "Clear expectations and timeline",
      "Support plan + checkpoint",
    ],
    strong_answer_signals: [
      "1:1",
      "expectations",
      "feedback",
      "PIP",
      "support",
      "timeline",
    ],
  },
  {
    id: "em-hiring-signal",
    track_id: "em-interview",
    topic_id: "em-hiring",
    category: "Hiring",
    prompt: "What signals tell you a Staff candidate is ready versus still senior IC? How do you probe in an interview?",
    hints: [
      "Influence without authority",
      "Ambiguity handling",
      "System ownership stories",
    ],
    strong_answer_signals: [
      "signal",
      "Staff",
      "influence",
      "ambiguity",
      "ownership",
      "bar",
    ],
  },
  {
    id: "em-exec-update",
    track_id: "em-interview",
    topic_id: "em-exec",
    category: "Exec communication",
    prompt: "Your roadmap slipped two weeks. How do you update an exec in 90 seconds?",
    hints: [
      "Status in one line",
      "Cause without excuses",
      "Decision you need",
    ],
    strong_answer_signals: [
      "exec",
      "status",
      "risk",
      "decision",
      "timeline",
      "impact",
    ],
  },
  {
    id: "em-reorg",
    track_id: "em-interview",
    topic_id: "em-org",
    category: "Org design",
    prompt: "When would you reorganize a team, and how do you minimize delivery risk during the change?",
    hints: [
      "Problem the org is solving",
      "Transition plan",
      "Communication cadence",
    ],
    strong_answer_signals: [
      "reorg",
      "ownership",
      "transition",
      "communication",
      "capacity",
      "risk",
    ],
  },
  {
    id: "em-conflict-skip",
    track_id: "em-interview",
    topic_id: "em-people",
    category: "Conflict",
    prompt: "Two senior engineers escalate past each other to you. How do you resolve it without becoming the bottleneck?",
    hints: [
      "Reset shared goals",
      "Facilitate a decision framework",
      "Document owners",
    ],
    strong_answer_signals: [
      "conflict",
      "facilitate",
      "decision",
      "owner",
      "escalate",
      "align",
    ],
  },
  {
    id: "em-delivery-risk",
    track_id: "em-interview",
    topic_id: "em-delivery",
    category: "Delivery",
    prompt: "A critical launch is at risk. How do you triage scope, people, and communication in the next 48 hours?",
    hints: [
      "Cut to must-have outcomes",
      "Staffing and unblocking",
      "External comms plan",
    ],
    strong_answer_signals: [
      "triage",
      "scope",
      "unblock",
      "comms",
      "risk",
      "launch",
    ],
  },
  {
    id: "em-transform-ai",
    track_id: "em-interview",
    topic_id: "em-transform",
    category: "Transformation",
    prompt: "Leadership wants “every team using AI.” How do you turn that slogan into a durable engineering change?",
    hints: [
      "Pilot with clear ROI",
      "Platform + enablement",
      "Guardrails and metrics",
    ],
    strong_answer_signals: [
      "AI",
      "pilot",
      "enablement",
      "platform",
      "metric",
      "adoption",
    ],
  },
  {
    id: "java-ai-choose-model",
    track_id: "java-to-ai",
    topic_id: "ai-path",
    category: "Architecture",
    prompt: "When do you choose a hosted LLM API versus self-hosting an open model for a Java backend product?",
    hints: [
      "Latency, cost, compliance",
      "Ops burden",
      "Product iteration speed",
    ],
    strong_answer_signals: [
      "API",
      "self-host",
      "cost",
      "compliance",
      "latency",
      "ops",
    ],
  },
  {
    id: "java-rag-chunk",
    track_id: "java-to-ai",
    topic_id: "ai-rag",
    category: "RAG",
    prompt: "Explain how you would chunk and embed a large internal wiki for RAG. What breaks if chunking is wrong?",
    hints: [
      "Chunk size vs overlap",
      "Metadata filters",
      "Failure modes: missed context / noise",
    ],
    strong_answer_signals: [
      "chunk",
      "embed",
      "vector",
      "metadata",
      "retrieval",
      "context",
    ],
  },
  {
    id: "java-agent-tools",
    track_id: "java-to-ai",
    topic_id: "ai-agents",
    category: "Agents",
    prompt: "Design a tool-calling agent that can query tickets and create a summary. How do you prevent unsafe actions?",
    hints: [
      "Allowlisted tools",
      "Human approval for writes",
      "Observation/logging",
    ],
    strong_answer_signals: [
      "tool",
      "allowlist",
      "approval",
      "agent",
      "audit",
      "schema",
    ],
  },
  {
    id: "java-eval-gate",
    track_id: "java-to-ai",
    topic_id: "ai-evals",
    category: "Evals",
    prompt: "What offline and online evals would you require before shipping an LLM feature to 10% of users?",
    hints: [
      "Golden set quality",
      "Online metrics: thumbs, escalation",
      "Kill switch",
    ],
    strong_answer_signals: [
      "eval",
      "golden",
      "online",
      "regression",
      "gate",
      "metric",
    ],
  },
  {
    id: "java-cost-control",
    track_id: "java-to-ai",
    topic_id: "ai-ops",
    category: "LLM Ops",
    prompt: "Your LLM bill spiked 3x overnight. How do you diagnose and stop the bleed without killing the feature?",
    hints: [
      "Token attribution by route",
      "Caching / cheaper model",
      "Rate limits",
    ],
    strong_answer_signals: [
      "cost",
      "tokens",
      "cache",
      "rate limit",
      "trace",
      "budget",
    ],
  },
  {
    id: "java-rag-vs-fine",
    track_id: "java-to-ai",
    topic_id: "ai-rag",
    category: "RAG",
    prompt: "A stakeholder asks to fine-tune instead of RAG. How do you decide?",
    hints: [
      "Freshness of knowledge",
      "Behavioral style vs facts",
      "Cost and iteration speed",
    ],
    strong_answer_signals: [
      "fine-tune",
      "RAG",
      "freshness",
      "facts",
      "cost",
      "decide",
    ],
  },
  {
    id: "j2p-collections",
    track_id: "java-to-python",
    topic_id: "j2p-syntax",
    category: "Syntax",
    prompt: "Compare Java List/Map idioms to Python list/dict comprehensions. When is each clearer?",
    hints: [
      "Show a small transform example",
      "Mention readability vs performance",
      "Call out mutation pitfalls",
    ],
    strong_answer_signals: [
      "list",
      "dict",
      "comprehension",
      "idiom",
      "readable",
      "mutable",
    ],
  },
  {
    id: "j2p-typing-strict",
    track_id: "java-to-python",
    topic_id: "j2p-typing",
    category: "Typing",
    prompt: "How would you introduce mypy or pyright into a Java-style team coming to Python?",
    hints: [
      "Start on public APIs",
      "CI gate gradually",
      "Show a typed FastAPI example",
    ],
    strong_answer_signals: [
      "mypy",
      "type hint",
      "CI",
      "FastAPI",
      "gradual",
      "interface",
    ],
  },
  {
    id: "j2p-async-vs-threads",
    track_id: "java-to-python",
    topic_id: "j2p-async",
    category: "Async",
    prompt: "When do you use asyncio versus threads/processes in Python after years of Java concurrency?",
    hints: [
      "I/O bound vs CPU bound",
      "Event loop mental model",
      "Common deadlock mistakes",
    ],
    strong_answer_signals: [
      "asyncio",
      "thread",
      "process",
      "I/O",
      "CPU",
      "event loop",
    ],
  },
  {
    id: "j2p-fastapi-auth",
    track_id: "java-to-python",
    topic_id: "j2p-fastapi",
    category: "APIs",
    prompt: "Design JWT auth for a FastAPI service the way you would in Spring Security — what is similar and different?",
    hints: [
      "Dependency injection for auth",
      "Middleware vs Depends",
      "Error model",
    ],
    strong_answer_signals: [
      "JWT",
      "Depends",
      "middleware",
      "auth",
      "401",
      "FastAPI",
    ],
  },
  {
    id: "j2p-oop-vs-funcs",
    track_id: "java-to-python",
    topic_id: "j2p-oop",
    category: "OOP",
    prompt: "When should a Java engineer prefer plain functions and modules over classes in Python?",
    hints: [
      "Statefulness test",
      "Protocol/duck typing",
      "Keep classes for real entities",
    ],
    strong_answer_signals: [
      "function",
      "module",
      "class",
      "protocol",
      "state",
      "simple",
    ],
  },
  {
    id: "j2p-mindset-tests",
    track_id: "java-to-python",
    topic_id: "j2p-mindset",
    category: "Mindset",
    prompt: "How does your testing strategy change moving from JUnit to pytest?",
    hints: [
      "Fixtures vs @Before",
      "Parametrize",
      "Fast feedback loops",
    ],
    strong_answer_signals: [
      "pytest",
      "fixture",
      "parametrize",
      "assert",
      "unit",
      "integration",
    ],
  },
  {
    id: "java-equals-hash",
    track_id: "java",
    topic_id: "java-oop",
    category: "OOP",
    prompt: "Explain equals/hashCode contracts and a production bug you have seen when they break.",
    hints: [
      "Symmetry/transitivity",
      "HashMap implications",
      "Defensive pattern",
    ],
    strong_answer_signals: [
      "equals",
      "hashCode",
      "HashMap",
      "contract",
      "bug",
      "immutable",
    ],
  },
  {
    id: "java-streams",
    track_id: "java",
    topic_id: "java-oop",
    category: "Language",
    prompt: "When do you prefer Streams over classic loops in Java, and when do you avoid them?",
    hints: [
      "Readability",
      "Performance pitfalls",
      "Checked exceptions",
    ],
    strong_answer_signals: [
      "stream",
      "loop",
      "lazy",
      "collect",
      "readable",
      "perf",
    ],
  },
  {
    id: "java-virtual-threads",
    track_id: "java",
    topic_id: "java-concurrency",
    category: "Concurrency",
    prompt: "How would you use virtual threads (Project Loom) for a high-concurrency IO service?",
    hints: [
      "Blocking IO friendliness",
      "Pinning pitfalls",
      "Migration from thread pools",
    ],
    strong_answer_signals: [
      "virtual thread",
      "Loom",
      "blocking",
      "pool",
      "scalability",
      "IO",
    ],
  },
  {
    id: "java-spring-tx",
    track_id: "java",
    topic_id: "java-spring",
    category: "Spring",
    prompt: "Explain @Transactional boundaries and a failure mode with self-invocation or lazy loading.",
    hints: [
      "Proxy behavior",
      "Propagation",
      "LazyInitializationException",
    ],
    strong_answer_signals: [
      "transactional",
      "proxy",
      "lazy",
      "propagation",
      "session",
      "Spring",
    ],
  },
  {
    id: "java-spring-rest",
    track_id: "java",
    topic_id: "java-spring",
    category: "APIs",
    prompt: "Design a versioned REST API in Spring Boot with validation and consistent error responses.",
    hints: [
      "DTO validation",
      "Problem Details / error shape",
      "Versioning strategy",
    ],
    strong_answer_signals: [
      "REST",
      "validation",
      "DTO",
      "version",
      "error",
      "Spring Boot",
    ],
  },
  {
    id: "py-gil",
    track_id: "python",
    topic_id: "python-basics",
    category: "Language",
    prompt: "Explain the GIL in practical terms for a web service. When does it matter?",
    hints: [
      "CPU vs IO",
      "multiprocessing",
      "native extensions",
    ],
    strong_answer_signals: [
      "GIL",
      "CPU",
      "IO",
      "multiprocess",
      "thread",
      "CPython",
    ],
  },
  {
    id: "py-decorators",
    track_id: "python",
    topic_id: "python-basics",
    category: "Language",
    prompt: "Explain decorators with a real FastAPI or logging example.",
    hints: [
      "Functions as values",
      "wraps",
      "Common pitfalls",
    ],
    strong_answer_signals: [
      "decorator",
      "wraps",
      "closure",
      "fastapi",
      "logging",
      "reuse",
    ],
  },
  {
    id: "py-async-cancel",
    track_id: "python",
    topic_id: "python-async",
    category: "Async",
    prompt: "How do you handle cancellation and timeouts safely in asyncio?",
    hints: [
      "wait_for",
      "task groups",
      "Cleanup in finally",
    ],
    strong_answer_signals: [
      "timeout",
      "cancel",
      "asyncio",
      "finally",
      "task",
      "shield",
    ],
  },
  {
    id: "py-fastapi-deps",
    track_id: "python",
    topic_id: "python-fastapi",
    category: "APIs",
    prompt: "How do FastAPI dependencies help structure auth, DB sessions, and testing?",
    hints: [
      "Depends graph",
      "Override in tests",
      "Lifecycle",
    ],
    strong_answer_signals: [
      "Depends",
      "session",
      "auth",
      "override",
      "test",
      "lifecycle",
    ],
  },
  {
    id: "py-pydantic",
    track_id: "python",
    topic_id: "python-fastapi",
    category: "Validation",
    prompt: "When do you use Pydantic models versus plain dicts in an API?",
    hints: [
      "Validation at boundary",
      "Serialization",
      "Performance notes",
    ],
    strong_answer_signals: [
      "Pydantic",
      "validation",
      "schema",
      "serialize",
      "boundary",
      "typed",
    ],
  },
  {
    id: "js-promises",
    track_id: "javascript",
    topic_id: "js-async",
    category: "Async",
    prompt: "Compare callbacks, promises, and async/await. When does Promise.allSettled matter?",
    hints: [
      "Error propagation",
      "Parallelism",
      "Partial failure",
    ],
    strong_answer_signals: [
      "promise",
      "async",
      "await",
      "allSettled",
      "error",
      "parallel",
    ],
  },
  {
    id: "js-event-loop",
    track_id: "javascript",
    topic_id: "js-async",
    category: "Runtime",
    prompt: "Explain the browser/Node event loop with microtasks vs macrotasks.",
    hints: [
      "Call stack",
      "queue types",
      "Why UI jank happens",
    ],
    strong_answer_signals: [
      "event loop",
      "microtask",
      "macrotask",
      "queue",
      "jank",
      "tick",
    ],
  },
  {
    id: "js-dom-perf",
    track_id: "javascript",
    topic_id: "js-dom",
    category: "DOM",
    prompt: "How do you batch DOM updates and avoid layout thrashing?",
    hints: [
      "Read/write separation",
      "DocumentFragment",
      "Virtualize long lists",
    ],
    strong_answer_signals: [
      "reflow",
      "batch",
      "fragment",
      "layout",
      "virtualize",
      "DOM",
    ],
  },
  {
    id: "js-modules",
    track_id: "javascript",
    topic_id: "js-language",
    category: "Modules",
    prompt: "ESM vs CommonJS: what breaks in the browser and in Node tooling?",
    hints: [
      "Static vs dynamic import",
      "Default export pitfalls",
      "Bundlers",
    ],
    strong_answer_signals: [
      "ESM",
      "CommonJS",
      "import",
      "export",
      "bundle",
      "module",
    ],
  },
  {
    id: "ts-unknown",
    track_id: "typescript",
    topic_id: "ts-basics",
    category: "Types",
    prompt: "When do you use unknown versus any, and how do you narrow safely?",
    hints: [
      "Force narrowing",
      "Avoid any escape hatches",
      "Example with JSON parse",
    ],
    strong_answer_signals: [
      "unknown",
      "any",
      "narrow",
      "typeof",
      "guard",
      "safe",
    ],
  },
  {
    id: "ts-utility",
    track_id: "typescript",
    topic_id: "ts-basics",
    category: "Types",
    prompt: "Explain Pick, Omit, Partial, and Required with an API DTO example.",
    hints: [
      "Derive types from a source of truth",
      "Avoid duplication",
      "Readonly where useful",
    ],
    strong_answer_signals: [
      "Pick",
      "Omit",
      "Partial",
      "Required",
      "DTO",
      "derive",
    ],
  },
  {
    id: "ts-generics-api",
    track_id: "typescript",
    topic_id: "ts-generics",
    category: "Generics",
    prompt: "Design a typed fetch helper with generics for response data and error shapes.",
    hints: [
      "Generic parameters",
      "Constraints",
      "Inference",
    ],
    strong_answer_signals: [
      "generic",
      "fetch",
      "infer",
      "constraint",
      "Response",
      "typed",
    ],
  },
  {
    id: "ts-discriminated",
    track_id: "typescript",
    topic_id: "ts-generics",
    category: "Advanced",
    prompt: "Show a discriminated union for UI state: loading | error | success.",
    hints: [
      "tag field",
      "exhaustive switch",
      "Narrowing benefits",
    ],
    strong_answer_signals: [
      "discriminated",
      "union",
      "exhaustive",
      "narrow",
      "state",
      "tag",
    ],
  },
  {
    id: "react-state-lift",
    track_id: "react",
    topic_id: "react-components",
    category: "State",
    prompt: "When do you lift state up versus use context or a store?",
    hints: [
      "Who needs the data",
      "Prop drilling pain",
      "Render cost",
    ],
    strong_answer_signals: [
      "lift state",
      "context",
      "store",
      "props",
      "render",
      "owner",
    ],
  },
  {
    id: "react-effect-deps",
    track_id: "react",
    topic_id: "react-effects",
    category: "Effects",
    prompt: "Explain a stale closure bug in useEffect and how you fix it.",
    hints: [
      "Dependency array",
      "Functional updates",
      "Cleanup",
    ],
    strong_answer_signals: [
      "useEffect",
      "deps",
      "stale",
      "cleanup",
      "functional update",
      "bug",
    ],
  },
  {
    id: "react-memo",
    track_id: "react",
    topic_id: "react-components",
    category: "Performance",
    prompt: "When does React.memo / useMemo help, and when is it wasted work?",
    hints: [
      "Pure children",
      "Unstable props",
      "Measure first",
    ],
    strong_answer_signals: [
      "memo",
      "useMemo",
      "render",
      "props",
      "perf",
      "profile",
    ],
  },
  {
    id: "react-forms",
    track_id: "react",
    topic_id: "react-components",
    category: "Forms",
    prompt: "Controlled vs uncontrolled inputs — how do you choose for a complex form?",
    hints: [
      "Validation needs",
      "Performance",
      "Libraries",
    ],
    strong_answer_signals: [
      "controlled",
      "uncontrolled",
      "form",
      "validation",
      "state",
      "input",
    ],
  },
  {
    id: "node-event-loop",
    track_id: "nodejs",
    topic_id: "node-runtime",
    category: "Runtime",
    prompt: "Explain Node’s event loop phases and a bug caused by blocking the loop.",
    hints: [
      "Phases overview",
      "CPU-heavy sync work",
      "Offload strategies",
    ],
    strong_answer_signals: [
      "event loop",
      "blocking",
      "phase",
      "worker",
      "CPU",
      "async",
    ],
  },
  {
    id: "node-streams",
    track_id: "nodejs",
    topic_id: "node-runtime",
    category: "Streams",
    prompt: "When do you use streams for file/HTTP processing instead of buffering?",
    hints: [
      "Memory bounds",
      "Backpressure",
      "Error propagation",
    ],
    strong_answer_signals: [
      "stream",
      "backpressure",
      "buffer",
      "pipe",
      "memory",
      "HTTP",
    ],
  },
  {
    id: "node-express-errors",
    track_id: "nodejs",
    topic_id: "node-apis",
    category: "APIs",
    prompt: "Design centralized error handling for an Express API.",
    hints: [
      "Async errors",
      "Status mapping",
      "Logging without leaking internals",
    ],
    strong_answer_signals: [
      "error middleware",
      "async",
      "status",
      "logging",
      "Express",
      "handler",
    ],
  },
  {
    id: "node-auth-jwt",
    track_id: "nodejs",
    topic_id: "node-apis",
    category: "Auth",
    prompt: "Implement JWT auth in Node: access vs refresh tokens and revocation basics.",
    hints: [
      "Short-lived access",
      "Refresh storage",
      "Logout/revoke",
    ],
    strong_answer_signals: [
      "JWT",
      "refresh",
      "revoke",
      "auth",
      "cookie",
      "expire",
    ],
  },
  {
    id: "node-prod-obs",
    track_id: "nodejs",
    topic_id: "node-prod",
    category: "Production",
    prompt: "What observability do you require before calling a Node service production-ready?",
    hints: [
      "Structured logs",
      "Metrics/traces",
      "Health checks",
    ],
    strong_answer_signals: [
      "observability",
      "metrics",
      "trace",
      "health",
      "logs",
      "SLO",
    ],
  },
  {
    id: "html-landmarks",
    track_id: "html",
    topic_id: "html-semantic",
    category: "Semantic",
    prompt: "How do landmark elements (header/nav/main/aside/footer) help accessibility and SEO?",
    hints: [
      "Screen reader navigation",
      "One main",
      "Avoid div soup",
    ],
    strong_answer_signals: [
      "landmark",
      "semantic",
      "a11y",
      "main",
      "nav",
      "SEO",
    ],
  },
  {
    id: "html-forms-a11y",
    track_id: "html",
    topic_id: "html-forms",
    category: "Forms",
    prompt: "Build an accessible form: labels, errors, and required fields.",
    hints: [
      "label for/id",
      "aria-describedby",
      "Error announcement",
    ],
    strong_answer_signals: [
      "label",
      "aria",
      "required",
      "error",
      "form",
      "accessible",
    ],
  },
  {
    id: "html-img-alt",
    track_id: "html",
    topic_id: "html-a11y",
    category: "A11y",
    prompt: "When should alt text be empty, and how do you describe complex images?",
    hints: [
      "Decorative vs informative",
      "Long descriptions",
      "Charts",
    ],
    strong_answer_signals: [
      "alt",
      "decorative",
      "informative",
      "aria",
      "image",
      "a11y",
    ],
  },
  {
    id: "html-tables",
    track_id: "html",
    topic_id: "html-semantic",
    category: "Tables",
    prompt: "How do you mark up a data table accessibly with headers and captions?",
    hints: [
      "th scope",
      "caption",
      "Avoid layout tables",
    ],
    strong_answer_signals: [
      "table",
      "th",
      "scope",
      "caption",
      "accessible",
      "data",
    ],
  },
  {
    id: "html-dialog",
    track_id: "html",
    topic_id: "html-a11y",
    category: "A11y",
    prompt: "How should a modal dialog behave for keyboard and screen reader users?",
    hints: [
      "Focus trap",
      "Escape to close",
      "aria-modal",
    ],
    strong_answer_signals: [
      "dialog",
      "focus",
      "escape",
      "aria-modal",
      "keyboard",
      "modal",
    ],
  },
  {
    id: "css-specificity",
    track_id: "css",
    topic_id: "css-box",
    category: "Cascade",
    prompt: "Explain specificity and a maintainable strategy to avoid !important wars.",
    hints: [
      "Inline vs classes vs IDs",
      "Layering / BEM",
      "When !important is ok",
    ],
    strong_answer_signals: [
      "specificity",
      "cascade",
      "important",
      "BEM",
      "layer",
      "selector",
    ],
  },
  {
    id: "css-flex-wrap",
    track_id: "css",
    topic_id: "css-layout",
    category: "Flexbox",
    prompt: "How do you build a responsive card row with flexbox that wraps cleanly?",
    hints: [
      "flex-basis",
      "gap",
      "min-width pitfalls",
    ],
    strong_answer_signals: [
      "flex",
      "wrap",
      "gap",
      "basis",
      "responsive",
      "card",
    ],
  },
  {
    id: "css-grid-areas",
    track_id: "css",
    topic_id: "css-layout",
    category: "Grid",
    prompt: "When do you choose CSS Grid over Flexbox for a page layout?",
    hints: [
      "Two-dimensional layout",
      "Template areas",
      "Alignment",
    ],
    strong_answer_signals: [
      "grid",
      "flex",
      "template",
      "area",
      "2D",
      "layout",
    ],
  },
  {
    id: "css-clamp",
    track_id: "css",
    topic_id: "css-responsive",
    category: "Responsive",
    prompt: "Explain fluid type/spacing with clamp() and when media queries are still needed.",
    hints: [
      "min preferred max",
      "Container queries",
      "Breakpoints for layout swaps",
    ],
    strong_answer_signals: [
      "clamp",
      "fluid",
      "media query",
      "container",
      "responsive",
      "type",
    ],
  },
  {
    id: "css-stacking",
    track_id: "css",
    topic_id: "css-box",
    category: "Positioning",
    prompt: "Explain stacking contexts and a bug where z-index “doesn’t work.”",
    hints: [
      "New stacking context triggers",
      "Isolation",
      "Practical fix",
    ],
    strong_answer_signals: [
      "z-index",
      "stacking",
      "context",
      "position",
      "isolation",
      "overlay",
    ],
  },
  {
    id: "js-this-bind",
    track_id: "javascript",
    topic_id: "js-language",
    category: "Language",
    prompt: "Explain how `this` works in regular functions vs arrow functions, and when you reach for `.bind` or a class field.",
    hints: [
      "Call-site rules for function this",
      "Arrow functions close over lexical this",
      "Event handlers and extracting methods",
    ],
    strong_answer_signals: [
      "this",
      "arrow",
      "bind",
      "lexical",
      "call site",
      "method",
    ],
  },
  {
    id: "ts-react-events",
    track_id: "typescript",
    topic_id: "ts-react",
    category: "React + TS",
    prompt: "How do you type React event handlers and form change events without resorting to `any`?",
    hints: [
      "React.ChangeEvent / FormEvent",
      "Generic HTML element types",
      "Infer from onChange props when possible",
    ],
    strong_answer_signals: [
      "ChangeEvent",
      "FormEvent",
      "HTMLInputElement",
      "handler",
      "generic",
      "props",
    ],
  },
  {
    id: "react-list-stable-ids",
    track_id: "react",
    topic_id: "react-lists",
    category: "Lists",
    prompt: "You reordered a list and inputs kept the wrong values. What went wrong with keys, and how do you pick stable identities?",
    hints: [
      "Index keys vs business ids",
      "Reconciliation remount vs reuse",
      "When index keys are acceptable",
    ],
    strong_answer_signals: [
      "key",
      "identity",
      "reconcile",
      "index",
      "stable",
      "remount",
    ],
  },
  {
    id: "java-ai-grounding",
    track_id: "java-to-ai",
    topic_id: "ai-agents",
    category: "Safety",
    prompt: "How do you keep an LLM agent from inventing answers when tools or retrieval return nothing useful?",
    hints: [
      "Abstain / clarify when evidence is weak",
      "Cite retrieved chunks or tool results",
      "Separate retrieval failure from model failure",
    ],
    strong_answer_signals: [
      "grounding",
      "abstain",
      "citation",
      "tool",
      "retrieval",
      "hallucination",
    ],
  },
  {
    id: "java-ai-react-loop",
    track_id: "java-to-ai",
    topic_id: "ai-agents",
    category: "Agents",
    prompt: "Explain the ReAct pattern for an agent that answers support tickets with tools. What are the steps in each loop, and how do you bound runaway tool use?",
    hints: [
      "Reason → Act → Observe cycle",
      "Cap steps/tokens; allowlist tools",
      "Stop when done or confidence is low",
    ],
    strong_answer_signals: [
      "react",
      "reason",
      "act",
      "observe",
      "tool",
      "bound",
      "loop",
      "allowlist",
    ],
  },
  {
    id: "java-ai-langgraph-state",
    track_id: "java-to-ai",
    topic_id: "ai-agents",
    category: "LangGraph",
    prompt: "When would you choose a LangGraph-style stateful graph over a linear LangChain chain for an agentic workflow? Walk through nodes, edges, and checkpoints.",
    hints: [
      "Branching, retries, human gates → graph",
      "Checkpoint state for resume/audit",
      "Known linear path → chain is enough",
    ],
    strong_answer_signals: [
      "langgraph",
      "state",
      "node",
      "edge",
      "checkpoint",
      "branch",
      "retry",
      "human",
    ],
  },
  {
    id: "java-ai-multi-agent",
    track_id: "java-to-ai",
    topic_id: "ai-agents",
    category: "Multi-agent",
    prompt: "Design a small multi-agent system (researcher + writer + reviewer) for drafting an internal RFC. How do you hand off work, share memory, and prevent conflicting edits?",
    hints: [
      "Clear roles and ownership of artifacts",
      "Shared state vs message passing",
      "Reviewer gate before publish",
    ],
    strong_answer_signals: [
      "multi-agent",
      "role",
      "handoff",
      "memory",
      "review",
      "state",
      "conflict",
      "gate",
    ],
  },
  {
    id: "java-ai-mcp-tools",
    track_id: "java-to-ai",
    topic_id: "ai-agents",
    category: "Tools",
    prompt: "How would you expose internal APIs to an agent via MCP or function calling safely? Cover schema design, authz, and what never goes in the tool surface.",
    hints: [
      "Typed schemas + server-side validation",
      "Least-privilege credentials",
      "No raw shell / unrestricted SQL",
    ],
    strong_answer_signals: [
      "mcp",
      "schema",
      "authz",
      "validate",
      "tool",
      "least privilege",
      "allowlist",
      "audit",
    ],
  },
  {
    id: "java-ai-hitl",
    track_id: "java-to-ai",
    topic_id: "ai-agents",
    category: "Safety",
    prompt: "Where do you put human-in-the-loop gates in an agent that can create tickets, refunds, and emails? Give a concrete approval policy.",
    hints: [
      "Reads auto; irreversible writes need approval",
      "Risk tiers by dollar amount / audience",
      "Timeouts and audit trail",
    ],
    strong_answer_signals: [
      "human",
      "approval",
      "irreversible",
      "refund",
      "audit",
      "policy",
      "risk",
      "gate",
    ],
  },
  {
    id: "java-ai-agent-vs-workflow",
    track_id: "java-to-ai",
    topic_id: "ai-agents",
    category: "Architecture",
    prompt: "A PM wants an 'AI agent' for invoice processing. When do you push back for a deterministic workflow with LLM steps instead of a free-form agent loop?",
    hints: [
      "Stable steps → workflow + LLM nodes",
      "Open-ended exploration → agent",
      "Compliance and SLAs favor deterministic paths",
    ],
    strong_answer_signals: [
      "workflow",
      "deterministic",
      "agent",
      "sla",
      "compliance",
      "step",
      "llm",
      "tradeoff",
    ],
  },
  {
    id: "java-ai-agentic-rag",
    track_id: "java-to-ai",
    topic_id: "ai-rag",
    category: "RAG",
    prompt: "Compare naive single-shot RAG with an agentic retrieve-then-refine loop. When is the extra retrieval hop worth the latency and cost?",
    hints: [
      "Hard questions need multi-hop retrieval",
      "Budget hops; cache intermediate results",
      "Eval faithfulness vs latency",
    ],
    strong_answer_signals: [
      "agentic",
      "retrieval",
      "multi-hop",
      "latency",
      "cost",
      "refine",
      "faithfulness",
      "rag",
    ],
  },
  {
    id: "java-ai-rag-authz",
    track_id: "java-to-ai",
    topic_id: "ai-rag",
    category: "RAG",
    prompt: "How do you keep RAG from leaking documents a user isn't entitled to see — at index time and at query time?",
    hints: [
      "Metadata filters on tenant/role",
      "Never retrieve then filter in the prompt alone",
      "Test negative entitlement cases",
    ],
    strong_answer_signals: [
      "entitlement",
      "authz",
      "metadata",
      "filter",
      "tenant",
      "leak",
      "index",
      "query",
    ],
  },
  {
    id: "java-ai-agent-evals",
    track_id: "java-to-ai",
    topic_id: "ai-evals",
    category: "Evals",
    prompt: "How do you evaluate an agentic workflow beyond final answer quality — including tool choice, trajectory length, and unsafe actions?",
    hints: [
      "Trajectory / step-level rubrics",
      "Golden tool sequences for common tasks",
      "Hard fail on unsafe tool calls",
    ],
    strong_answer_signals: [
      "trajectory",
      "tool",
      "eval",
      "unsafe",
      "step",
      "rubric",
      "golden",
      "agent",
    ],
  },
  {
    id: "java-ai-prompt-patterns",
    track_id: "java-to-ai",
    topic_id: "ai-path",
    category: "Prompting",
    prompt: "Explain prompt chaining vs a single mega-prompt for an agentic backend feature. Give a production example where chaining wins.",
    hints: [
      "Smaller steps = easier eval and retries",
      "Isolate retrieval, planning, and drafting",
      "Mega-prompts hide failure modes",
    ],
    strong_answer_signals: [
      "chain",
      "prompt",
      "step",
      "eval",
      "retry",
      "isolate",
      "production",
      "failure",
    ],
  },
  {
    id: "java-ai-agent-observability",
    track_id: "java-to-ai",
    topic_id: "ai-ops",
    category: "LLM Ops",
    prompt: "What would you put in an observability stack for production agents — traces, metrics, and alerts — so on-call can debug a bad tool loop at 2am?",
    hints: [
      "Trace every LLM + tool span",
      "Alert on loop length, error rate, cost spikes",
      "Redact secrets from logs",
    ],
    strong_answer_signals: [
      "trace",
      "metric",
      "alert",
      "tool",
      "loop",
      "cost",
      "observ",
      "on-call",
    ],
  },
  {
    id: "java-ai-model-routing",
    track_id: "java-to-ai",
    topic_id: "ai-ops",
    category: "LLM Ops",
    prompt: "Design model routing for an agentic assistant: cheap model for planning/classification, stronger model for final answers. How do you keep quality while cutting spend?",
    hints: [
      "Route by task difficulty / risk",
      "Escalate on low confidence",
      "Re-run evals after routing changes",
    ],
    strong_answer_signals: [
      "routing",
      "cheap",
      "strong",
      "confidence",
      "cost",
      "quality",
      "escalat",
      "eval",
    ],
  },
]

export function localQuestions(trackId: string): TutorQuestion[] {
  return QUESTIONS.filter((q) => q.track_id === trackId)
}

export function localFeedback(input: {
  track_id: TrackId
  question_id?: string | null
  custom_prompt?: string | null
  answer: string
  input_mode?: 'text' | 'voice'
}): Feedback {
  const mode = input.input_mode ?? 'text'
  const text = input.answer.trim()
  const lower = text.toLowerCase()
  const words = lower.match(/[a-z0-9']+/g) ?? []
  const customPrompt = (input.custom_prompt || '').trim()

  if (customPrompt) {
    const promptTokens = (customPrompt.toLowerCase().match(/[a-z0-9']+/g) ?? [])
      .filter((t) => t.length > 3)
      .slice(0, 12)
    const overlap = promptTokens.filter((t) => lower.includes(t)).length
    let score = 2
    if (words.length >= 80) score += 1
    if (overlap >= 2) score += 1
    if (/\d|%|uptime|million|latency|users|team/.test(lower)) score += 1
    score = Math.max(1, Math.min(5, score))

    const strengths: string[] = []
    const gaps: string[] = []
    if (words.length >= 60) {
      strengths.push('Enough length for a spoken interview answer.')
    } else {
      gaps.push(
        'Expand to ~90–120 seconds: context → what you did → outcome.',
      )
    }
    if (overlap >= 2) {
      strengths.push('Answer stays on the question you asked.')
    } else {
      gaps.push(
        'Name the key terms from your question early so the answer feels targeted.',
      )
    }
    if (/\b(first|then|so|because|tradeoff|result|impact|decided|owned)\b/.test(lower)) {
      strengths.push('Has a narrative spine (decision/result language).')
    } else {
      gaps.push(
        'Add structure: open with the answer, then ownership, tradeoff, metric.',
      )
    }

    const fillers = [
      'um',
      'uh',
      'like',
      'you know',
      'sort of',
      'kind of',
      'basically',
      'actually',
      'i mean',
    ]
    const delivery_tips: string[] = []
    if (mode === 'voice') {
      const found = fillers.filter((f) => new RegExp(`\\b${f}\\b`).test(lower))
      if (found.length) {
        delivery_tips.push(
          `Reduce filler words (${found.slice(0, 4).join(', ')}). Pause instead.`,
        )
      } else {
        delivery_tips.push(
          'Clean delivery — few filler words. Keep that in live interviews.',
        )
      }
      if (words.length < 70) {
        delivery_tips.push(
          'Interview answers usually need ~90–120 seconds. Add context → action → outcome.',
        )
      }
    }

    return {
      score,
      summary: `Custom-question rubric ${score}/5. ${
        mode === 'voice'
          ? 'Voice mode: includes spoken grammar and delivery tips.'
          : 'Offline coaching for your own prompt.'
      }`,
      strengths: strengths.length
        ? strengths
        : ['You attempted a full answer — good start.'],
      gaps: gaps.length
        ? gaps
        : ['Tighten structure and end on a measurable outcome.'],
      better_answer: [
        'Stronger spoken answer for YOUR question:',
        '1) Open with a one-sentence direct answer (no filler).',
        '2) Context: the system/situation the question implies.',
        '3) Ownership + decision/tradeoff specific to the prompt.',
        '4) Outcome with a metric — then stop.',
        `Stay anchored to: ${customPrompt.slice(0, 180)}${customPrompt.length > 180 ? '…' : ''}`,
      ].join('\n'),
      next_drill:
        'Retry the same custom question out loud — tighter open, clearer metric.',
      provider: 'browser-custom-rubric',
      delivery_tips,
      input_mode: mode,
    }
  }

  const question = QUESTIONS.find(
    (q) => q.id === input.question_id && q.track_id === input.track_id,
  )
  if (!question) {
    throw new Error('Unknown question')
  }

  const hits = question.strong_answer_signals.filter((s) => lower.includes(s))

  let score = 2
  if (words.length >= 80) score += 1
  if (hits.length >= 2) score += 1
  if (hits.length >= 4 || /\d|%/.test(text)) score += 1
  score = Math.max(1, Math.min(5, score))

  const strengths: string[] = []
  const gaps: string[] = []

  if (words.length >= 60) {
    strengths.push('Enough detail to sound senior — not a one-liner.')
  } else {
    gaps.push(
      'Expand with context, decision, and outcome (aim for ~90–120 seconds spoken).',
    )
  }
  if (hits.length) {
    strengths.push(`Hit key signals: ${hits.slice(0, 4).join(', ')}.`)
  } else {
    gaps.push(
      `Weave in concepts like: ${question.strong_answer_signals.slice(0, 4).join(', ')}.`,
    )
  }
  if (/\d|%|uptime|million|team/.test(lower)) {
    strengths.push('Includes concrete scale or metrics — interviewers love this.')
  } else {
    gaps.push('Add one concrete example or metric when possible.')
  }

  const fillers = ['um', 'uh', 'like', 'you know', 'sort of', 'kind of', 'basically', 'actually', 'i mean']
  const delivery_tips: string[] = []
  if (mode === 'voice') {
    const found = fillers.filter((f) => new RegExp(`\\b${f}\\b`).test(lower))
    if (found.length) {
      delivery_tips.push(
        `Reduce filler words (${found.slice(0, 4).join(', ')}). Pause instead.`,
      )
    } else {
      delivery_tips.push('Clean delivery — few filler words. Keep that in live interviews.')
    }
    if (words.length < 70) {
      delivery_tips.push(
        'Interview answers usually need ~90–120 seconds. Add context → action → outcome.',
      )
    }
    if (!/[.!?]/.test(text)) {
      delivery_tips.push(
        'Add natural sentence endings when you speak — it helps grammar and pacing.',
      )
    }
    if (found.filter((f) => (lower.match(new RegExp(`\\b${f}\\b`, 'g')) || []).length >= 3).length >= 2) {
      score = Math.max(1, score - 1)
      gaps.push('Spoken delivery had repeated fillers — practice a cleaner take.')
    }
  }

  return {
    score,
    summary: `Rubric score ${score}/5 for ${question.category.toLowerCase()}. ${
      mode === 'voice'
        ? 'Voice mode: includes spoken grammar and delivery tips.'
        : 'Running in free static hosting mode.'
    }`,
    strengths: strengths.length
      ? strengths
      : ['You attempted a full answer — good start.'],
    gaps: gaps.length
      ? gaps
      : ['Tighten structure and end on a measurable outcome.'],
    better_answer:
      mode === 'voice'
        ? [
            'Stronger spoken answer shape:',
            '1) Open in one clear sentence (no filler).',
            '2) Context: who/what system.',
            '3) Ownership + decision/tradeoff.',
            '4) Outcome with metric — then stop.',
            `Hint to include: ${question.hints.join(', ')}.`,
          ].join('\n')
        : [
            'Stronger shape for this prompt:',
            '1) Context: who/what system.',
            '2) Ownership: what you owned.',
            '3) Decision/tradeoff.',
            '4) Outcome with metric.',
            `Hint to include: ${question.hints.join(', ')}.`,
          ].join('\n'),
    next_drill:
      mode === 'voice'
        ? 'Record the same answer once more out loud — cut fillers and end on the metric.'
        : (question.hints[0] ?? 'Practice out loud once, timed.'),
    provider: 'browser-rubric',
    delivery_tips,
    input_mode: mode,
  }
}
