export type PathVideo = {
  id: string
  title: string
  channel: string
  duration: string
  why: string
  youtubeId?: string
  playlistId?: string
  url: string
}

export type PathPhase = {
  id: string
  step: number
  title: string
  blurb: string
  careerTip: string
  videos: PathVideo[]
}

/** Broad validated YouTube library for Data Engineer → Snowflake + Agentic AI (oEmbed-checked). */
export const SNOWFLAKE_PATH: PathPhase[] = [
  {
    id: 'de-foundations',
    step: 1,
    title: 'Data engineering foundations',
    blurb: 'SQL fluency, pipelines, and modern warehouse concepts — the bar before Snowflake syntax.',
    careerTip: 'Interviewers want you to explain warehouses vs lakes, ELT vs ETL, and why dimensional models still matter.',
    videos: [
      {
        id: 'de-foundations-PHsC_t0j1dU',
        title: 'Data Engineering Course for Beginners',
        channel: 'freeCodeCamp.org',
        duration: 'Video',
        why: 'Validated learning resource from freeCodeCamp.org.',
        youtubeId: 'PHsC_t0j1dU',
        url: 'https://www.youtube.com/watch?v=PHsC_t0j1dU',
      },
      {
        id: 'de-foundations-HXV3zeQKqGY',
        title: 'SQL Tutorial - Full Database Course for Beginners',
        channel: 'freeCodeCamp.org',
        duration: 'Video',
        why: 'Validated learning resource from freeCodeCamp.org.',
        youtubeId: 'HXV3zeQKqGY',
        url: 'https://www.youtube.com/watch?v=HXV3zeQKqGY',
      },
      {
        id: 'de-foundations-T23Bs75F7ZQ',
        title: 'Data Engineering with Python and AI/LLMs – Data Loading Tutorial',
        channel: 'freeCodeCamp.org',
        duration: 'Video',
        why: 'Validated learning resource from freeCodeCamp.org.',
        youtubeId: 'T23Bs75F7ZQ',
        url: 'https://www.youtube.com/watch?v=T23Bs75F7ZQ',
      },
      {
        id: 'de-foundations-wyGAYa2UMXQ',
        title: 'What Is Data Engineering - Why Is Data Engineering Important?',
        channel: 'Seattle Data Guy',
        duration: 'Video',
        why: 'Validated learning resource from Seattle Data Guy.',
        youtubeId: 'wyGAYa2UMXQ',
        url: 'https://www.youtube.com/watch?v=wyGAYa2UMXQ',
      },
      {
        id: 'de-foundations--ClWgwC0Sbw',
        title: 'What Is The Modern Data Stack - Intro To Data Infrastructure Part 1',
        channel: 'Seattle Data Guy',
        duration: 'Video',
        why: 'Validated learning resource from Seattle Data Guy.',
        youtubeId: '-ClWgwC0Sbw',
        url: 'https://www.youtube.com/watch?v=-ClWgwC0Sbw',
      },
      {
        id: 'de-foundations-eD-AeRMefiU',
        title: 'Build A Data Stack That Lasts - How To Ensure Your Data Infrastructure Is Maintainable',
        channel: 'Seattle Data Guy',
        duration: 'Video',
        why: 'Validated learning resource from Seattle Data Guy.',
        youtubeId: 'eD-AeRMefiU',
        url: 'https://www.youtube.com/watch?v=eD-AeRMefiU',
      },
      {
        id: 'de-foundations-pkoSi8DjTl4',
        title: 'What Is A Reverse ETL - And Why Is The Modern Data Stack Obsessed With It?',
        channel: 'Seattle Data Guy',
        duration: 'Video',
        why: 'Validated learning resource from Seattle Data Guy.',
        youtubeId: 'pkoSi8DjTl4',
        url: 'https://www.youtube.com/watch?v=pkoSi8DjTl4',
      },
      {
        id: 'de-foundations-kW8_l57w74g',
        title: 'Top Courses To Become A Data Engineer In 2022',
        channel: 'Seattle Data Guy',
        duration: 'Video',
        why: 'Validated learning resource from Seattle Data Guy.',
        youtubeId: 'kW8_l57w74g',
        url: 'https://www.youtube.com/watch?v=kW8_l57w74g',
      },
      {
        id: 'de-foundations-zZVQluYDwYY',
        title: 'Netflix Data Analysis | DBT (databuildtool) Tutorial Course | End-To-End Project',
        channel: 'Darshil Parmar',
        duration: 'Video',
        why: 'Validated learning resource from Darshil Parmar.',
        youtubeId: 'zZVQluYDwYY',
        url: 'https://www.youtube.com/watch?v=zZVQluYDwYY',
      },
      {
        id: 'de-foundations-fQte57VWmxc',
        title: 'Don\'t put toy dataset projects on your resume!',
        channel: 'codebasics',
        duration: 'Video',
        why: 'Validated learning resource from codebasics.',
        youtubeId: 'fQte57VWmxc',
        url: 'https://www.youtube.com/watch?v=fQte57VWmxc',
      },
    ],
  },
  {
    id: 'snowflake-core',
    step: 2,
    title: 'Snowflake core',
    blurb: 'Architecture, warehouses, SnowSQL, loading, Time Travel, Zero-Copy Cloning, and Secure Data Sharing.',
    careerTip: 'Be ready to whiteboard cloud services architecture, virtual warehouses, and recovery/cloning tradeoffs.',
    videos: [
      {
        id: 'snowflake-core-h78-o40MnRM',
        title: 'What is Snowflake? Learn Snowflake in 30 Minutes',
        channel: 'codebasics',
        duration: 'Video',
        why: 'Validated learning resource from codebasics.',
        youtubeId: 'h78-o40MnRM',
        url: 'https://www.youtube.com/watch?v=h78-o40MnRM',
      },
      {
        id: 'snowflake-core-VIJH7TZXkaA',
        title: 'Learn Snowflake in 10 Minutes| High Paying Skills | Step by Step Hands-On Guide',
        channel: 'Darshil Parmar',
        duration: 'Video',
        why: 'Validated learning resource from Darshil Parmar.',
        youtubeId: 'VIJH7TZXkaA',
        url: 'https://www.youtube.com/watch?v=VIJH7TZXkaA',
      },
      {
        id: 'snowflake-core-6nmvYrHEEkI',
        title: 'Snowflake Full Course for Beginner to Advanced | Learn Snowflake in One Video |Job & Interview Ready',
        channel: 'Cloudlearningyard',
        duration: 'Video',
        why: 'Validated learning resource from Cloudlearningyard.',
        youtubeId: '6nmvYrHEEkI',
        url: 'https://www.youtube.com/watch?v=6nmvYrHEEkI',
      },
      {
        id: 'snowflake-core-TeD5zshkdjY',
        title: 'Getting Started: Introduction To Snowflake Virtual Warehouses',
        channel: 'Snowflake Developers',
        duration: 'Video',
        why: 'Validated learning resource from Snowflake Developers.',
        youtubeId: 'TeD5zshkdjY',
        url: 'https://www.youtube.com/watch?v=TeD5zshkdjY',
      },
      {
        id: 'snowflake-core-IocdgUB94KQ',
        title: '#3 | Snowflake Architecture | Snowflake Tutorial for Beginners',
        channel: 'Data Engineering Simplified',
        duration: 'Video',
        why: 'Validated learning resource from Data Engineering Simplified.',
        youtubeId: 'IocdgUB94KQ',
        url: 'https://www.youtube.com/watch?v=IocdgUB94KQ',
      },
      {
        id: 'snowflake-core-8Qqt0hGTsbQ',
        title: '#2 Snowflake Architecture in depth || How Snowflake works',
        channel: 'Cloudlearningyard',
        duration: 'Video',
        why: 'Validated learning resource from Cloudlearningyard.',
        youtubeId: '8Qqt0hGTsbQ',
        url: 'https://www.youtube.com/watch?v=8Qqt0hGTsbQ',
      },
      {
        id: 'snowflake-core-ZNxcQbENyzQ',
        title: 'Snowflake 101: How To Install, Configure & Use SnowSQL',
        channel: 'Snowflake Developers',
        duration: 'Video',
        why: 'Validated learning resource from Snowflake Developers.',
        youtubeId: 'ZNxcQbENyzQ',
        url: 'https://www.youtube.com/watch?v=ZNxcQbENyzQ',
      },
      {
        id: 'snowflake-core-gcuX7ZYY-ec',
        title: 'Snowflake SnowSQL Full Course | Beginner to Expert Step-by-Step Guide',
        channel: 'Data Engineering Simplified',
        duration: 'Video',
        why: 'Validated learning resource from Data Engineering Simplified.',
        youtubeId: 'gcuX7ZYY-ec',
        url: 'https://www.youtube.com/watch?v=gcuX7ZYY-ec',
      },
      {
        id: 'snowflake-core-PLba2xJ7yxHB',
        title: 'SnowSQL Client - Complete Master Class | Hands-On Tutorial From Beginners To Expert | SnowSQL 101 Tutorial',
        channel: 'Data Engineering Simplified',
        duration: 'Playlist',
        why: 'Validated learning resource from Data Engineering Simplified.',
        playlistId: 'PLba2xJ7yxHB5h780W6sGrcaau5e7453s5',
        url: 'https://www.youtube.com/playlist?list=PLba2xJ7yxHB5h780W6sGrcaau5e7453s5',
      },
      {
        id: 'snowflake-core-PLba2xJ7yxHB',
        title: 'How To Load Data Into Snowflake  - Masterclass',
        channel: 'Data Engineering Simplified',
        duration: 'Playlist',
        why: 'Validated learning resource from Data Engineering Simplified.',
        playlistId: 'PLba2xJ7yxHB6NPEv8pp7j3zWibLZzwjvO',
        url: 'https://www.youtube.com/playlist?list=PLba2xJ7yxHB6NPEv8pp7j3zWibLZzwjvO',
      },
      {
        id: 'snowflake-core-ygZ04M2YcKs',
        title: 'Loading Data Into Snowflake| Upload CSV/GZIP & Large Files | Ch-01 Snowflake Data Loading Tutorial',
        channel: 'Data Engineering Simplified',
        duration: 'Video',
        why: 'Validated learning resource from Data Engineering Simplified.',
        youtubeId: 'ygZ04M2YcKs',
        url: 'https://www.youtube.com/watch?v=ygZ04M2YcKs',
      },
      {
        id: 'snowflake-core-Ss76gupmc3w',
        title: 'User Stage & CSV Data Loading Into Snowflake | Using SnowSQL CLI | Ch-02 | Snowflake Tutorial',
        channel: 'Data Engineering Simplified',
        duration: 'Video',
        why: 'Validated learning resource from Data Engineering Simplified.',
        youtubeId: 'Ss76gupmc3w',
        url: 'https://www.youtube.com/watch?v=Ss76gupmc3w',
      },
      {
        id: 'snowflake-core-PK_C0QATV5k',
        title: 'Snowflake 101: Recovering Data with Time Travel',
        channel: 'Snowflake Developers',
        duration: 'Video',
        why: 'Validated learning resource from Snowflake Developers.',
        youtubeId: 'PK_C0QATV5k',
        url: 'https://www.youtube.com/watch?v=PK_C0QATV5k',
      },
      {
        id: 'snowflake-core-9k8ADXunhIk',
        title: 'What is Snowflake Time Travel | Chapter-14 | Snowflake Hands-on Tutorial',
        channel: 'Data Engineering Simplified',
        duration: 'Video',
        why: 'Validated learning resource from Data Engineering Simplified.',
        youtubeId: '9k8ADXunhIk',
        url: 'https://www.youtube.com/watch?v=9k8ADXunhIk',
      },
      {
        id: 'snowflake-core-uGCpwoQOQzQ',
        title: 'A Quick Look At Zero Copy Cloning In Snowflake',
        channel: 'Snowflake Developers',
        duration: 'Video',
        why: 'Validated learning resource from Snowflake Developers.',
        youtubeId: 'uGCpwoQOQzQ',
        url: 'https://www.youtube.com/watch?v=uGCpwoQOQzQ',
      },
      {
        id: 'snowflake-core-2d6d-zZMXtA',
        title: 'Snowflake Data Sharing | Chapter-16 | Snowflake Hands-on Tutorial',
        channel: 'Data Engineering Simplified',
        duration: 'Video',
        why: 'Validated learning resource from Data Engineering Simplified.',
        youtubeId: '2d6d-zZMXtA',
        url: 'https://www.youtube.com/watch?v=2d6d-zZMXtA',
      },
      {
        id: 'snowflake-core-MIUU_Lhu4-U',
        title: '#30 Snowflake Secure Data Sharing || Data Sharing in Snowflake',
        channel: 'Cloudlearningyard',
        duration: 'Video',
        why: 'Validated learning resource from Cloudlearningyard.',
        youtubeId: 'MIUU_Lhu4-U',
        url: 'https://www.youtube.com/watch?v=MIUU_Lhu4-U',
      },
      {
        id: 'snowflake-core-oLfAAtPBm70',
        title: '#2 | Snowflake Free Trial Edition & Self Registration | Snowflake Tutorial for Beginners',
        channel: 'Data Engineering Simplified',
        duration: 'Video',
        why: 'Validated learning resource from Data Engineering Simplified.',
        youtubeId: 'oLfAAtPBm70',
        url: 'https://www.youtube.com/watch?v=oLfAAtPBm70',
      },
      {
        id: 'snowflake-core-PLba2xJ7yxHB',
        title: 'Snowflake Tutorial For Beginners',
        channel: 'Data Engineering Simplified',
        duration: 'Playlist',
        why: 'Validated learning resource from Data Engineering Simplified.',
        playlistId: 'PLba2xJ7yxHB73xHFsyu0YViu3Hi6Ckxzj',
        url: 'https://www.youtube.com/playlist?list=PLba2xJ7yxHB73xHFsyu0YViu3Hi6Ckxzj',
      },
    ],
  },
  {
    id: 'snowflake-engineers',
    step: 3,
    title: 'Snowflake for engineers',
    blurb: 'Streams/Tasks, Dynamic Tables, Snowpark (Python), dbt on Snowflake, and performance/cost habits.',
    careerTip: 'Own incremental pipelines end-to-end: CDC → transforms → freshness SLAs → credit burn.',
    videos: [
      {
        id: 'snowflake-engineers-DXI0GDSwE_E',
        title: 'Snowflake Stream & Change Data Capture | Chapter-17 | Snowflake Hands-on Tutorial',
        channel: 'Data Engineering Simplified',
        duration: 'Video',
        why: 'Validated learning resource from Data Engineering Simplified.',
        youtubeId: 'DXI0GDSwE_E',
        url: 'https://www.youtube.com/watch?v=DXI0GDSwE_E',
      },
      {
        id: 'snowflake-engineers-YZ29egrAcLw',
        title: 'The Benefits of Dynamic Tables',
        channel: 'Snowflake Developers',
        duration: 'Video',
        why: 'Validated learning resource from Snowflake Developers.',
        youtubeId: 'YZ29egrAcLw',
        url: 'https://www.youtube.com/watch?v=YZ29egrAcLw',
      },
      {
        id: 'snowflake-engineers-bk1uzVM8aN8',
        title: 'Building Cost-Effective, Real-Time Pipelines with Snowflake Dynamic Tables',
        channel: 'Snowflake Inc.',
        duration: 'Video',
        why: 'Validated learning resource from Snowflake Inc..',
        youtubeId: 'bk1uzVM8aN8',
        url: 'https://www.youtube.com/watch?v=bk1uzVM8aN8',
      },
      {
        id: 'snowflake-engineers-yTUneS1WXao',
        title: 'How to Build Python Data Engineering Pipelines with Snowpark',
        channel: 'Snowflake Developers',
        duration: 'Video',
        why: 'Validated learning resource from Snowflake Developers.',
        youtubeId: 'yTUneS1WXao',
        url: 'https://www.youtube.com/watch?v=yTUneS1WXao',
      },
      {
        id: 'snowflake-engineers-PLavJpcg8cl1',
        title: 'Snowpark',
        channel: 'Snowflake Developers',
        duration: 'Playlist',
        why: 'Validated learning resource from Snowflake Developers.',
        playlistId: 'PLavJpcg8cl1G8JyqH4NyLcFZ9xxp_gGy7',
        url: 'https://www.youtube.com/playlist?list=PLavJpcg8cl1G8JyqH4NyLcFZ9xxp_gGy7',
      },
      {
        id: 'snowflake-engineers-PLba2xJ7yxHB',
        title: 'What Is Snowpark | Learn Everything About Snowflake Snowpark',
        channel: 'Data Engineering Simplified',
        duration: 'Playlist',
        why: 'Validated learning resource from Data Engineering Simplified.',
        playlistId: 'PLba2xJ7yxHB4yPg3pUrobdzeMxk4mP24S',
        url: 'https://www.youtube.com/playlist?list=PLba2xJ7yxHB4yPg3pUrobdzeMxk4mP24S',
      },
      {
        id: 'snowflake-engineers-PLba2xJ7yxHB',
        title: 'Snowpark Tutorial | Learn Snowpark Using Python API Examples | Scenario Playlist',
        channel: 'Data Engineering Simplified',
        duration: 'Playlist',
        why: 'Validated learning resource from Data Engineering Simplified.',
        playlistId: 'PLba2xJ7yxHB7RNDaCSrw3wqJwaxKgj1O5',
        url: 'https://www.youtube.com/playlist?list=PLba2xJ7yxHB7RNDaCSrw3wqJwaxKgj1O5',
      },
      {
        id: 'snowflake-engineers-CS0FDfPSBUA',
        title: 'Snowpark Python API & RSA (Key Pair) Authentication Example',
        channel: 'Data Engineering Simplified',
        duration: 'Video',
        why: 'Validated learning resource from Data Engineering Simplified.',
        youtubeId: 'CS0FDfPSBUA',
        url: 'https://www.youtube.com/watch?v=CS0FDfPSBUA',
      },
      {
        id: 'snowflake-engineers-Dr0WlzgcQ30',
        title: 'Snowflake 2 Snowpark Using User ID & Password | Snowpark Python Tutorial With Example',
        channel: 'Data Engineering Simplified',
        duration: 'Video',
        why: 'Validated learning resource from Data Engineering Simplified.',
        youtubeId: 'Dr0WlzgcQ30',
        url: 'https://www.youtube.com/watch?v=Dr0WlzgcQ30',
      },
      {
        id: 'snowflake-engineers-7tToBddZ_is',
        title: '#02 | What Is NOT Snowpark? | Learn on  Spark vs Snowpark',
        channel: 'Data Engineering Simplified',
        duration: 'Video',
        why: 'Validated learning resource from Data Engineering Simplified.',
        youtubeId: '7tToBddZ_is',
        url: 'https://www.youtube.com/watch?v=7tToBddZ_is',
      },
      {
        id: 'snowflake-engineers-w7C7OkmYPFs',
        title: 'Running dbt Projects On Snowflake',
        channel: 'Snowflake Developers',
        duration: 'Video',
        why: 'Validated learning resource from Snowflake Developers.',
        youtubeId: 'w7C7OkmYPFs',
        url: 'https://www.youtube.com/watch?v=w7C7OkmYPFs',
      },
      {
        id: 'snowflake-engineers-kbCkwhySV_I',
        title: 'Configure Snowflake for dbt Cloud',
        channel: 'dbt Labs',
        duration: 'Video',
        why: 'Validated learning resource from dbt Labs.',
        youtubeId: 'kbCkwhySV_I',
        url: 'https://www.youtube.com/watch?v=kbCkwhySV_I',
      },
      {
        id: 'snowflake-engineers-TS46i3-l2kI',
        title: 'dbt Labs + Snowflake: Why SQL and Python go perfectly well together',
        channel: 'dbt Labs',
        duration: 'Video',
        why: 'Validated learning resource from dbt Labs.',
        youtubeId: 'TS46i3-l2kI',
        url: 'https://www.youtube.com/watch?v=TS46i3-l2kI',
      },
      {
        id: 'snowflake-engineers-3SZSDKEZqoA',
        title: 'Airbnb End-To-End Data Engineering Project (For Beginners) | DBT + Snowflake + AWS',
        channel: 'Ansh Lamba',
        duration: 'Video',
        why: 'Validated learning resource from Ansh Lamba.',
        youtubeId: '3SZSDKEZqoA',
        url: 'https://www.youtube.com/watch?v=3SZSDKEZqoA',
      },
      {
        id: 'snowflake-engineers-kbuv4HHVeSk',
        title: 'Snowflake Cost Optimization Strategies | 7 Tips To Reduce Your Snowflake Costs',
        channel: 'Data Engineering Simplified',
        duration: 'Video',
        why: 'Validated learning resource from Data Engineering Simplified.',
        youtubeId: 'kbuv4HHVeSk',
        url: 'https://www.youtube.com/watch?v=kbuv4HHVeSk',
      },
      {
        id: 'snowflake-engineers-PLavJpcg8cl1',
        title: 'Cost Optimization',
        channel: 'Snowflake Developers',
        duration: 'Playlist',
        why: 'Validated learning resource from Snowflake Developers.',
        playlistId: 'PLavJpcg8cl1Epd5ziAjdpvkO9NyzVgsy-',
        url: 'https://www.youtube.com/playlist?list=PLavJpcg8cl1Epd5ziAjdpvkO9NyzVgsy-',
      },
      {
        id: 'snowflake-engineers-GJPrdAoJB7g',
        title: 'Introducing Snowpark Connect for Apache Spark',
        channel: 'Snowflake Developers',
        duration: 'Video',
        why: 'Validated learning resource from Snowflake Developers.',
        youtubeId: 'GJPrdAoJB7g',
        url: 'https://www.youtube.com/watch?v=GJPrdAoJB7g',
      },
      {
        id: 'snowflake-engineers-aENolfHIvLI',
        title: 'How To Run Existing Spark Code Directly On Snowflake With Snowpark Connect',
        channel: 'Snowflake Developers',
        duration: 'Video',
        why: 'Validated learning resource from Snowflake Developers.',
        youtubeId: 'aENolfHIvLI',
        url: 'https://www.youtube.com/watch?v=aENolfHIvLI',
      },
      {
        id: 'snowflake-engineers-PLba2xJ7yxHB',
        title: 'Snowflake SQL Scripting For Stored Procedure - Complete Tutorial With Examples',
        channel: 'Data Engineering Simplified',
        duration: 'Playlist',
        why: 'Validated learning resource from Data Engineering Simplified.',
        playlistId: 'PLba2xJ7yxHB5NksIHMPirkHhOoEG3-K09',
        url: 'https://www.youtube.com/playlist?list=PLba2xJ7yxHB5NksIHMPirkHhOoEG3-K09',
      },
    ],
  },
  {
    id: 'snowflake-ai-cortex',
    step: 4,
    title: 'Snowflake AI / Cortex',
    blurb: 'Cortex LLM functions, Analyst, Search, and Document AI — AI features that run next to governed data.',
    careerTip: 'Frame Cortex as platform AI: governance + SQL-native functions, not a separate LLM sidecar.',
    videos: [
      {
        id: 'snowflake-ai-cortex-PLavJpcg8cl1',
        title: 'Cortex AI',
        channel: 'Snowflake Developers',
        duration: 'Playlist',
        why: 'Validated learning resource from Snowflake Developers.',
        playlistId: 'PLavJpcg8cl1Fz5IyYbMpvg0FDT8IANxam',
        url: 'https://www.youtube.com/playlist?list=PLavJpcg8cl1Fz5IyYbMpvg0FDT8IANxam',
      },
      {
        id: 'snowflake-ai-cortex-punK7CLS3Sg',
        title: 'Gen AI Boot Camp, Parts 1 and 2 | Working With Snowflake Cortex Analyst And Cortex Search',
        channel: 'Snowflake Developers',
        duration: 'Video',
        why: 'Validated learning resource from Snowflake Developers.',
        youtubeId: 'punK7CLS3Sg',
        url: 'https://www.youtube.com/watch?v=punK7CLS3Sg',
      },
      {
        id: 'snowflake-ai-cortex-CXoca9hDdaQ',
        title: 'Demo: Snowflake Cortex Analyst To Augment Business Intelligence With AI',
        channel: 'Snowflake Developers',
        duration: 'Video',
        why: 'Validated learning resource from Snowflake Developers.',
        youtubeId: 'CXoca9hDdaQ',
        url: 'https://www.youtube.com/watch?v=CXoca9hDdaQ',
      },
      {
        id: 'snowflake-ai-cortex-yXgFs31MWUw',
        title: 'Demo: Build A RAG Application With Snowflake Cortex Search | Summit 2024',
        channel: 'Snowflake Developers',
        duration: 'Video',
        why: 'Validated learning resource from Snowflake Developers.',
        youtubeId: 'yXgFs31MWUw',
        url: 'https://www.youtube.com/watch?v=yXgFs31MWUw',
      },
      {
        id: 'snowflake-ai-cortex-8iCKMw8kO3c',
        title: 'Snowflake Cortex Search Deep Dive — Indexing, Querying & Results Explained (Airbnb Dataset)',
        channel: 'DevTroops ',
        duration: 'Video',
        why: 'Validated learning resource from DevTroops .',
        youtubeId: '8iCKMw8kO3c',
        url: 'https://www.youtube.com/watch?v=8iCKMw8kO3c',
      },
      {
        id: 'snowflake-ai-cortex-jmdmf2FGbTQ',
        title: 'Snowflake AI services: Cortex Search',
        channel: 'Seemore Data',
        duration: 'Video',
        why: 'Validated learning resource from Seemore Data.',
        youtubeId: 'jmdmf2FGbTQ',
        url: 'https://www.youtube.com/watch?v=jmdmf2FGbTQ',
      },
      {
        id: 'snowflake-ai-cortex-3vCuoezBMEY',
        title: 'How to start using Snowflake Cortex LLM functions🔥: Python — Snowflake #1',
        channel: 'Code AI with Rok',
        duration: 'Video',
        why: 'Validated learning resource from Code AI with Rok.',
        youtubeId: '3vCuoezBMEY',
        url: 'https://www.youtube.com/watch?v=3vCuoezBMEY',
      },
      {
        id: 'snowflake-ai-cortex-bVq1I7VwC9s',
        title: 'FrostyLibrary: A Snowflake Cortex LLM Demo',
        channel: 'Snowflake Developers',
        duration: 'Video',
        why: 'Validated learning resource from Snowflake Developers.',
        youtubeId: 'bVq1I7VwC9s',
        url: 'https://www.youtube.com/watch?v=bVq1I7VwC9s',
      },
      {
        id: 'snowflake-ai-cortex-4RItxPcq4vk',
        title: 'Demo: LLM Serverless Fine-Tuning With Snowflake Cortex AI | Summit 2024',
        channel: 'Snowflake Developers',
        duration: 'Video',
        why: 'Validated learning resource from Snowflake Developers.',
        youtubeId: '4RItxPcq4vk',
        url: 'https://www.youtube.com/watch?v=4RItxPcq4vk',
      },
      {
        id: 'snowflake-ai-cortex-ztLylokOBjs',
        title: 'Snowflake Cortex AI SQL: Extracting Insights From Multimodal Customer Service Data | AI Bootcamp',
        channel: 'Snowflake Developers',
        duration: 'Video',
        why: 'Validated learning resource from Snowflake Developers.',
        youtubeId: 'ztLylokOBjs',
        url: 'https://www.youtube.com/watch?v=ztLylokOBjs',
      },
      {
        id: 'snowflake-ai-cortex-BuVrxMfmVFE',
        title: 'Snowflake Document AI Tutorial: Turn Unstructured Documents into Structured Data',
        channel: 'Snowflake Developers',
        duration: 'Video',
        why: 'Validated learning resource from Snowflake Developers.',
        youtubeId: 'BuVrxMfmVFE',
        url: 'https://www.youtube.com/watch?v=BuVrxMfmVFE',
      },
      {
        id: 'snowflake-ai-cortex-bvFn00mPRnw',
        title: 'Unlock the Power Of Your Documents With Snowflake Document AI',
        channel: 'Snowflake Developers',
        duration: 'Video',
        why: 'Validated learning resource from Snowflake Developers.',
        youtubeId: 'bvFn00mPRnw',
        url: 'https://www.youtube.com/watch?v=bvFn00mPRnw',
      },
      {
        id: 'snowflake-ai-cortex-CAjchjmsvIs',
        title: 'AI-Driven Processing Of Manufacturing Documents And Data With Document AI',
        channel: 'Snowflake Developers',
        duration: 'Video',
        why: 'Validated learning resource from Snowflake Developers.',
        youtubeId: 'CAjchjmsvIs',
        url: 'https://www.youtube.com/watch?v=CAjchjmsvIs',
      },
      {
        id: 'snowflake-ai-cortex-5XdcLSL_z_w',
        title: 'Part 1 | What is Cortex Analyst? Why It Matters | Basics of Snowflake Cortex & AI Data Agents',
        channel: 'AlgoChat',
        duration: 'Video',
        why: 'Validated learning resource from AlgoChat.',
        youtubeId: '5XdcLSL_z_w',
        url: 'https://www.youtube.com/watch?v=5XdcLSL_z_w',
      },
      {
        id: 'snowflake-ai-cortex-PLiFErliE7g4',
        title: 'Cortex Analyst on Snowflake — Complete Beginner to Expert Guide (AI Agent | Natural Language to Data | Snowflake AI)',
        channel: 'AlgoChat',
        duration: 'Playlist',
        why: 'Validated learning resource from AlgoChat.',
        playlistId: 'PLiFErliE7g4XLTRzStzh2Eh2voqDkfuIq',
        url: 'https://www.youtube.com/playlist?list=PLiFErliE7g4XLTRzStzh2Eh2voqDkfuIq',
      },
      {
        id: 'snowflake-ai-cortex-kOLTSvrDe60',
        title: 'AI Compliance Copilot: Automating Regulatory Search With Snowflake Cortex AI',
        channel: 'Snowflake Developers',
        duration: 'Video',
        why: 'Validated learning resource from Snowflake Developers.',
        youtubeId: 'kOLTSvrDe60',
        url: 'https://www.youtube.com/watch?v=kOLTSvrDe60',
      },
      {
        id: 'snowflake-ai-cortex-PLba2xJ7yxHB',
        title: 'Snowflake SnowPro GenAI Certification (GES-C01) Full Course & Tutorials',
        channel: 'Data Engineering Simplified',
        duration: 'Playlist',
        why: 'Validated learning resource from Data Engineering Simplified.',
        playlistId: 'PLba2xJ7yxHB7yKE34Pyei1Jr0bKMZWgos',
        url: 'https://www.youtube.com/playlist?list=PLba2xJ7yxHB7yKE34Pyei1Jr0bKMZWgos',
      },
    ],
  },
  {
    id: 'snowflake-agentic',
    step: 5,
    title: 'Snowflake agentic AI',
    blurb: 'Cortex Agents, Snowflake Intelligence, tool use, MCP, and agent apps that reason over warehouse data.',
    careerTip: 'Differentiate Analyst (text-to-SQL), Search (unstructured RAG), and Agents (orchestration + tools).',
    videos: [
      {
        id: 'snowflake-agentic-SDqyB-yWaAE',
        title: 'Getting Started With Cortex Agents',
        channel: 'Snowflake Developers',
        duration: 'Video',
        why: 'Validated learning resource from Snowflake Developers.',
        youtubeId: 'SDqyB-yWaAE',
        url: 'https://www.youtube.com/watch?v=SDqyB-yWaAE',
      },
      {
        id: 'snowflake-agentic-WP3OtjzeheE',
        title: 'Building Cortex Agents On Snowflake: Why It Matters And Best Practices',
        channel: 'Snowflake Developers',
        duration: 'Video',
        why: 'Validated learning resource from Snowflake Developers.',
        youtubeId: 'WP3OtjzeheE',
        url: 'https://www.youtube.com/watch?v=WP3OtjzeheE',
      },
      {
        id: 'snowflake-agentic-x4YXsGz8hvM',
        title: 'Cortex Agents | Built[By] Danmei Xu',
        channel: 'Snowflake Inc.',
        duration: 'Video',
        why: 'Validated learning resource from Snowflake Inc..',
        youtubeId: 'x4YXsGz8hvM',
        url: 'https://www.youtube.com/watch?v=x4YXsGz8hvM',
      },
      {
        id: 'snowflake-agentic-zSC_PLAULas',
        title: 'Building Agentic AI Applications on Snowflake: From Query to MCP | BUILD 2025',
        channel: 'Snowflake Developers',
        duration: 'Video',
        why: 'Validated learning resource from Snowflake Developers.',
        youtubeId: 'zSC_PLAULas',
        url: 'https://www.youtube.com/watch?v=zSC_PLAULas',
      },
      {
        id: 'snowflake-agentic-bLKDFv2A3PA',
        title: 'Agentic ML in Snowflake',
        channel: 'Snowflake Developers',
        duration: 'Video',
        why: 'Validated learning resource from Snowflake Developers.',
        youtubeId: 'bLKDFv2A3PA',
        url: 'https://www.youtube.com/watch?v=bLKDFv2A3PA',
      },
      {
        id: 'snowflake-agentic-wKvVkHO0fOw',
        title: '5 min to Build an AI agent using Cortex Code',
        channel: 'Snowflake Developers',
        duration: 'Video',
        why: 'Validated learning resource from Snowflake Developers.',
        youtubeId: 'wKvVkHO0fOw',
        url: 'https://www.youtube.com/watch?v=wKvVkHO0fOw',
      },
      {
        id: 'snowflake-agentic-JEzHZpe-ZSA',
        title: 'Build a Cortex Analyst in Snowflake Intelligence under 10 Mins!',
        channel: 'Somesh Sidhwani',
        duration: 'Video',
        why: 'Validated learning resource from Somesh Sidhwani.',
        youtubeId: 'JEzHZpe-ZSA',
        url: 'https://www.youtube.com/watch?v=JEzHZpe-ZSA',
      },
      {
        id: 'snowflake-agentic-4oxh6B4okqY',
        title: 'Snowflake CoWork Is Here – What’s New in Enterprise AI | Snowflake Summit 2026',
        channel: 'Snowflake Developers',
        duration: 'Video',
        why: 'Validated learning resource from Snowflake Developers.',
        youtubeId: '4oxh6B4okqY',
        url: 'https://www.youtube.com/watch?v=4oxh6B4okqY',
      },
      {
        id: 'snowflake-agentic-08kFtNOV9xE',
        title: 'From One Prompt to Production: Building with Snowflake CoCo',
        channel: 'Snowflake Developers',
        duration: 'Video',
        why: 'Validated learning resource from Snowflake Developers.',
        youtubeId: '08kFtNOV9xE',
        url: 'https://www.youtube.com/watch?v=08kFtNOV9xE',
      },
      {
        id: 'snowflake-agentic-BhwbA7lxfP0',
        title: 'Agentic AI Bootcamp: How LLMs Use SQL to Think, Query & Automate Data Tasks',
        channel: 'AI in Plain Text | Debabrata Pruseth',
        duration: 'Video',
        why: 'Validated learning resource from AI in Plain Text | Debabrata Pruseth.',
        youtubeId: 'BhwbA7lxfP0',
        url: 'https://www.youtube.com/watch?v=BhwbA7lxfP0',
      },
    ],
  },
  {
    id: 'career-interview',
    step: 6,
    title: 'Career / interview path',
    blurb: 'Data engineer + Snowflake interview drills — architecture stories, SQL, and scenario questions.',
    careerTip: 'Lead with a production pipeline story: volume, freshness, cost, failure modes, then Snowflake specifics.',
    videos: [
      {
        id: 'career-interview-W2L7Q3J-ei0',
        title: 'SQL Interview Questions For Data Scientists And Data Engineers - Tips For Practicing SQL Interviews',
        channel: 'Seattle Data Guy',
        duration: 'Video',
        why: 'Validated learning resource from Seattle Data Guy.',
        youtubeId: 'W2L7Q3J-ei0',
        url: 'https://www.youtube.com/watch?v=W2L7Q3J-ei0',
      },
      {
        id: 'career-interview-hFyqSYGmkyc',
        title: 'Snowflake Interview Prep Part 1 | Architecture Virtual Warehouses Core Concepts #Snowflake',
        channel: 'Time Variant',
        duration: 'Video',
        why: 'Validated learning resource from Time Variant.',
        youtubeId: 'hFyqSYGmkyc',
        url: 'https://www.youtube.com/watch?v=hFyqSYGmkyc',
      },
      {
        id: 'career-interview-PL__gObEGy1Y',
        title: 'Snowflake Hands-on Scenarios + Most Asked Interview Questions',
        channel: 'Cloudlearningyard',
        duration: 'Playlist',
        why: 'Validated learning resource from Cloudlearningyard.',
        playlistId: 'PL__gObEGy1Y5jmkhnNIY4uk4Na0Mjd_bK',
        url: 'https://www.youtube.com/playlist?list=PL__gObEGy1Y5jmkhnNIY4uk4Na0Mjd_bK',
      },
      {
        id: 'career-interview-eWUfc2vcmd4',
        title: 'Snowflake SnowPro Core Tutorial | Everything You Need to Pass the Certification',
        channel: 'Networks Professionals',
        duration: 'Video',
        why: 'Validated learning resource from Networks Professionals.',
        youtubeId: 'eWUfc2vcmd4',
        url: 'https://www.youtube.com/watch?v=eWUfc2vcmd4',
      },
      {
        id: 'career-interview-8olmZpqJ7jM',
        title: 'Snowflake Data Engineering with DBT & Airflow | Complete Course for Beginners to Advanced',
        channel: 'Visualpath Pro',
        duration: 'Video',
        why: 'Validated learning resource from Visualpath Pro.',
        youtubeId: '8olmZpqJ7jM',
        url: 'https://www.youtube.com/watch?v=8olmZpqJ7jM',
      },
      {
        id: 'career-interview-Bh5b_C2k3Bg',
        title: 'Top 20 Snowflake Interview Questions You Must Know',
        channel: 'KSR Datavizon',
        duration: 'Video',
        why: 'Validated learning resource from KSR Datavizon.',
        youtubeId: 'Bh5b_C2k3Bg',
        url: 'https://www.youtube.com/watch?v=Bh5b_C2k3Bg',
      },
      {
        id: 'career-interview-4JYirMYRQC8',
        title:
          'Snowflake Interview Questions and Answers for experienced - Data Engineer || SQL || scenario based',
        channel: 'Data Architect Studio',
        duration: 'Video',
        why: 'Validated learning resource from Data Architect Studio.',
        youtubeId: '4JYirMYRQC8',
        url: 'https://www.youtube.com/watch?v=4JYirMYRQC8',
      },
      {
        id: 'career-interview-FRdUAmyn600',
        title: 'Snowflake Interview Questions | Real-World Answers for Data Engineers',
        channel: 'DataengineerVS',
        duration: 'Video',
        why: 'Validated learning resource from DataengineerVS.',
        youtubeId: 'FRdUAmyn600',
        url: 'https://www.youtube.com/watch?v=FRdUAmyn600',
      },
      {
        id: 'career-interview-4LFnBS-Ywck',
        title:
          'Snowflake Interview Questions and Answers | Most Asked Snowflake Questions in Interview',
        channel: 'Praveen Kumar Bommisetty',
        duration: 'Video',
        why: 'Validated learning resource from Praveen Kumar Bommisetty.',
        youtubeId: '4LFnBS-Ywck',
        url: 'https://www.youtube.com/watch?v=4LFnBS-Ywck',
      },
      {
        id: 'career-interview-6Y-x1Dt-xWs',
        title:
          'Real time Snowflake ETL + Interview Scenario | Load Valid Data & Auto Send failure records to Client',
        channel: 'Cloudlearningyard',
        duration: 'Video',
        why: 'Validated learning resource from Cloudlearningyard.',
        youtubeId: '6Y-x1Dt-xWs',
        url: 'https://www.youtube.com/watch?v=6Y-x1Dt-xWs',
      },
      {
        id: 'career-interview-C3BuKL6-kFA',
        title:
          'Snowflake Real-Time Scenario: Automate Data Loads from S3 Dynamic Day-Wise Folders to Snowflake',
        channel: 'Cloudlearningyard',
        duration: 'Video',
        why: 'Validated learning resource from Cloudlearningyard.',
        youtubeId: 'C3BuKL6-kFA',
        url: 'https://www.youtube.com/watch?v=C3BuKL6-kFA',
      },
      {
        id: 'career-interview-KwEe5NcZMXM',
        title: 'The ABSOLUTE BEST Snowflake Interview Questions and Answers',
        channel: 'KSR Datavizon',
        duration: 'Video',
        why: 'Validated learning resource from KSR Datavizon.',
        youtubeId: 'KwEe5NcZMXM',
        url: 'https://www.youtube.com/watch?v=KwEe5NcZMXM',
      },
    ],
  },
]

export function allPathVideos(): PathVideo[] {
  return SNOWFLAKE_PATH.flatMap((p) => p.videos)
}

export function embedUrl(video: PathVideo): string {
  if (video.playlistId) {
    return `https://www.youtube.com/embed/videoseries?list=${video.playlistId}`
  }
  return `https://www.youtube.com/embed/${video.youtubeId}`
}

const PROGRESS_KEY = 'ats_snowflake_video_done'

export function loadVideoProgress(): Set<string> {
  try {
    const raw = localStorage.getItem(PROGRESS_KEY)
    if (!raw) return new Set()
    return new Set(JSON.parse(raw) as string[])
  } catch {
    return new Set()
  }
}

export function saveVideoProgress(done: Set<string>) {
  localStorage.setItem(PROGRESS_KEY, JSON.stringify([...done]))
}

